ConfigVersion = 5

[Audio]
InterpolationMode = 'Linear'
MidiInputPortId = ''
MidiInputPortType = 'None'
MidiOutputPortId = ''
MidiOutputPortType = 'None'
Mute = false
StepGranularity = 0
ThreadedSCSP = false
Volume = 0.80000001192092896

[CDBlock]
OverrideROM = false
ROMPath = ''
ReadSpeed = 2
UseLLE = false

[Cartridge]
AutoLoadGameCarts = true
Type = 'None'

    [Cartridge.BackupRAM]
    Capacity = '32Mbit'
    ImagePath = ''

    [Cartridge.DRAM]
    Capacity = '32Mbit'

    [Cartridge.ROM]
    ImagePath = ''

[GUI]
FrameRateOSDPosition = 'TopRight'
OverrideUIScale = false
RememberWindowGeometry = true
ShowFrameRateOSD = false
ShowGameNameOnTitleBar = true
ShowMessages = true
ShowPerformanceOnTitleBar = true
ShowSpeedIndicatorForAllSpeeds = false
UIScale = 1.0

[General]
AltSpeedFactor = 0.5
BoostEmuThreadPriority = true
BoostProcessPriority = true
CheckForUpdates = false
EnableRewindBuffer = false
IncludeNightlyBuilds = false
MainSpeedFactor = 1.0
PauseWhenUnfocused = false
PreloadDiscImagesToRAM = false
RememberLastLoadedDisc = false
RewindCompressionLevel = 12
ScreenshotScale = 2
StartPaused = false
UseAltSpeed = false

    [General.PathOverrides]
    BackupMemory = ''
    CDBlockROMImages = ''
    Dumps = ''
    ExportedBackups = ''
    IPLROMImages = ''
    PersistentState = ''
    ROMCartImages = ''
    SaveStates = ''
    Screenshots = ''

[Hotkeys]
DecreaseSpeed = [ 'Ctrl+Comma' ]
DecreaseSpeedLarge = [ 'Ctrl+Shift+Comma' ]
DecreaseVolume = [ 'Ctrl+MinusUnderscore' ]
DumpMemory = [ 'Ctrl+F11' ]
EjectDisc = [ 'Ctrl+W' ]
ExitApp = []
ForwardFrameStep = [ 'RightBracket' ]
HardReset = [ 'Ctrl+R' ]
IncreaseSpeed = [ 'Ctrl+Period' ]
IncreaseSpeedLarge = [ 'Ctrl+Shift+Period' ]
IncreaseVolume = [ 'Ctrl+EqualsPlus' ]
LoadDisc = [ 'Ctrl+O' ]
NextFrameRateOSDPosition = [ 'Ctrl+F1' ]
OpenCloseTray = [ 'Ctrl+T' ]
OpenSettings = [ 'F10' ]
PauseResume = [ 'Spacebar', 'Pause' ]
PreviousFrameRateOSDPosition = [ 'Ctrl+Shift+F1' ]
ResetButton = [ 'Shift+R' ]
ResetSpeed = [ 'Ctrl+Slash' ]
ReverseFrameStep = [ 'LeftBracket' ]
Rewind = [ 'Backspace' ]
RotateScreenClockwise = [ 'Ctrl+Apostrophe' ]
RotateScreenCounterclockwise = [ 'Ctrl+Shift+Apostrophe' ]
ShowMessageHistory = [ 'F1' ]
SoftReset = [ 'Ctrl+Shift+R' ]
TakeScreenshot = [ 'F12' ]
ToggleAlternateSpeed = [ 'Shift+Slash' ]
ToggleDebugTrace = [ 'F11' ]
ToggleFrameRateOSD = [ 'Shift+F1' ]
ToggleFullScreen = [ 'Alt+Return' ]
ToggleMute = [ 'Ctrl+M' ]
ToggleRewindBuffer = [ 'F8' ]
ToggleWindowedVideoOutput = [ 'F9' ]
TurboSpeed = [ 'Tab' ]
TurboSpeedHold = [ 'GraveAccent' ]

    [Hotkeys.SaveStates]
    LoadState1 = [ 'Ctrl+Alpha1' ]
    LoadState10 = [ 'Ctrl+Alpha0' ]
    LoadState2 = [ 'Ctrl+Alpha2' ]
    LoadState3 = [ 'Ctrl+Alpha3' ]
    LoadState4 = [ 'Ctrl+Alpha4' ]
    LoadState5 = [ 'Ctrl+Alpha5' ]
    LoadState6 = [ 'Ctrl+Alpha6' ]
    LoadState7 = [ 'Ctrl+Alpha7' ]
    LoadState8 = [ 'Ctrl+Alpha8' ]
    LoadState9 = [ 'Ctrl+Alpha9' ]
    QuickLoadState = [ 'F3' ]
    QuickSaveState = [ 'F2' ]
    SaveState1 = [ 'Shift+Alpha1' ]
    SaveState10 = [ 'Shift+Alpha0' ]
    SaveState2 = [ 'Shift+Alpha2' ]
    SaveState3 = [ 'Shift+Alpha3' ]
    SaveState4 = [ 'Shift+Alpha4' ]
    SaveState5 = [ 'Shift+Alpha5' ]
    SaveState6 = [ 'Shift+Alpha6' ]
    SaveState7 = [ 'Shift+Alpha7' ]
    SaveState8 = [ 'Shift+Alpha8' ]
    SaveState9 = [ 'Shift+Alpha9' ]
    SelectState1 = [ 'Alpha1' ]
    SelectState10 = [ 'Alpha0' ]
    SelectState2 = [ 'Alpha2' ]
    SelectState3 = [ 'Alpha3' ]
    SelectState4 = [ 'Alpha4' ]
    SelectState5 = [ 'Alpha5' ]
    SelectState6 = [ 'Alpha6' ]
    SelectState7 = [ 'Alpha7' ]
    SelectState8 = [ 'Alpha8' ]
    SelectState9 = [ 'Alpha9' ]
    UndoLoadState = [ 'Shift+F3' ]
    UndoSaveState = [ 'Shift+F2' ]

[Input.Gamepad]
AnalogToDigitalSensitivity = 0.20000000298023224
LSDeadzone = 0.15000000596046448
RSDeadzone = 0.15000000596046448

[Input.Mouse]
CaptureMode = 'SystemCursor'

[Input.Port1]
PeripheralType = 'ControlPad'

    [Input.Port1.AnalogPad.Binds]
    A = [ 'GamepadX@0', 'J' ]
    AnalogL = [ 'GamepadLeftTrigger@0' ]
    AnalogR = [ 'GamepadRightTrigger@0' ]
    AnalogStick = [ 'GamepadLeftStick@0' ]
    B = [ 'GamepadA@0', 'K' ]
    C = [ 'GamepadB@0', 'L' ]
    DPad = [ 'GamepadDPad@0' ]
    Down = [ 'S' ]
    L = [ 'Q' ]
    Left = [ 'A' ]
    R = [ 'E' ]
    Right = [ 'D' ]
    Start = [ 'GamepadStart@0', 'G', 'H', 'F' ]
    SwitchMode = [ 'GamepadLeftThumb@0', 'Ctrl+B' ]
    Up = [ 'W' ]
    X = [ 'GamepadLeftBumper@0', 'U' ]
    Y = [ 'GamepadY@0', 'I' ]
    Z = [ 'GamepadRightBumper@0', 'O' ]

    [Input.Port1.ArcadeRacer]
    Sensitivity = 0.5

        [Input.Port1.ArcadeRacer.Binds]
        A = [ 'J', 'GamepadX@0' ]
        B = [ 'K', 'GamepadA@0' ]
        C = [ 'L', 'GamepadB@0' ]
        Down = [ 'W', 'GamepadDpadUp@0', 'GamepadLeftTriggerButton@0' ]
        Start = [ 'F', 'G', 'H', 'GamepadStart@0' ]
        Up = [ 'S', 'GamepadDpadDown@0', 'GamepadRightTriggerButton@0' ]
        Wheel = [ 'GamepadLeftStickX@0' ]
        WheelLeft = [ 'A' ]
        WheelRight = [ 'D' ]
        X = [ 'U', 'GamepadLeftBumper@0' ]
        Y = [ 'I', 'GamepadY@0' ]
        Z = [ 'O', 'GamepadRightBumper@0' ]

    [Input.Port1.ControlPad.Binds]
    A = [ 'GamepadX@0', 'J' ]
    B = [ 'GamepadA@0', 'K' ]
    C = [ 'GamepadB@0', 'L' ]
    DPad = [ 'GamepadLeftStick@0', 'GamepadDPad@0' ]
    Down = [ 'S' ]
    L = [ 'GamepadLeftTriggerButton@0', 'Q' ]
    Left = [ 'A' ]
    R = [ 'GamepadRightTriggerButton@0', 'E' ]
    Right = [ 'D' ]
    Start = [ 'GamepadStart@0', 'H', 'G', 'F' ]
    Up = [ 'W' ]
    X = [ 'GamepadLeftBumper@0', 'U' ]
    Y = [ 'GamepadY@0', 'I' ]
    Z = [ 'GamepadRightBumper@0', 'O' ]

    [Input.Port1.MissionStick.Binds]
    A = [ 'X', 'GamepadX@0' ]
    B = [ 'C', 'GamepadA@0' ]
    C = [ 'V', 'GamepadB@0' ]
    L = [ 'Q', 'GamepadLeftThumb@0' ]
    MainDown = [ 'S' ]
    MainLeft = [ 'A' ]
    MainRight = [ 'D' ]
    MainStick = [ 'GamepadLeftStick@0', 'GamepadDPad@0' ]
    MainThrottle = [ 'GamepadLeftTrigger@0' ]
    MainThrottleDown = [ 'F' ]
    MainThrottleMax = [ 'Shift+R' ]
    MainThrottleMin = [ 'Shift+F' ]
    MainThrottleUp = [ 'R' ]
    MainUp = [ 'W' ]
    R = [ 'E', 'GamepadRightThumb@0' ]
    Start = [ 'G', 'GamepadStart@0' ]
    SubDown = [ 'K' ]
    SubLeft = [ 'J' ]
    SubRight = [ 'L' ]
    SubStick = [ 'GamepadRightStick@0' ]
    SubThrottle = [ 'GamepadRightTrigger@0' ]
    SubThrottleDown = [ 'H' ]
    SubThrottleMax = [ 'Shift+Y' ]
    SubThrottleMin = [ 'Shift+H' ]
    SubThrottleUp = [ 'Y' ]
    SubUp = [ 'I' ]
    SwitchMode = [ 'Ctrl+B', 'GamepadBack@0' ]
    X = [ 'B', 'GamepadLeftBumper@0' ]
    Y = [ 'N', 'GamepadY@0' ]
    Z = [ 'M', 'GamepadRightBumper@0' ]

    [Input.Port1.ShuttleMouse]
    Sensitivity = 4.0
    Speed = 30.0
    SpeedBoostFactor = 2.0

        [Input.Port1.ShuttleMouse.Binds]
        Left = [ 'GamepadA@0', 'J' ]
        Middle = [ 'GamepadX@0', 'K' ]
        Move = []
        MoveDown = [ 'S' ]
        MoveLeft = [ 'A' ]
        MoveRight = [ 'D' ]
        MoveUp = [ 'W' ]
        Right = [ 'GamepadB@0', 'L' ]
        SpeedBoost = [ 'GamepadLeftBumper@0', 'C' ]
        SpeedToggle = [ 'GamepadLeftTriggerButton@0', 'V' ]
        Start = [ 'GamepadStart@0', 'G', 'H', 'F' ]

    [Input.Port1.VirtuaGun]
    Speed = 200.0
    SpeedBoostFactor = 2.0

        [Input.Port1.VirtuaGun.Binds]
        Down = [ 'S' ]
        Left = [ 'A' ]
        Move = [ 'GamepadDPad@0', 'GamepadLeftStick@0' ]
        Recenter = [ 'R', 'GamepadLeftThumb@0' ]
        Reload = [ 'K', 'GamepadB@0' ]
        Right = [ 'D' ]
        SpeedBoost = [ 'L', 'GamepadLeftBumper@0' ]
        SpeedToggle = [ 'O', 'GamepadLeftTriggerButton@0' ]
        Start = [ 'F', 'G', 'H', 'GamepadStart@0' ]
        Trigger = [ 'J', 'GamepadA@0' ]
        Up = [ 'W' ]

        [Input.Port1.VirtuaGun.Crosshair]
        Color = [ 1.0, 0.5, 0.0, 0.87999999523162842 ]
        Radius = 15.0
        Rotation = 0.0
        StrokeColor = [ 0.0, 0.0, 0.0, 1.0 ]
        StrokeThickness = 0.25
        Thickness = 0.33000001311302185

[Input.Port2]
PeripheralType = 'ControlPad'

    [Input.Port2.AnalogPad.Binds]
    A = [ 'KeyPad1', 'GamepadX@1' ]
    AnalogL = [ 'GamepadLeftTrigger@1' ]
    AnalogR = [ 'GamepadRightTrigger@1' ]
    AnalogStick = [ 'GamepadLeftStick@1' ]
    B = [ 'KeyPad2', 'GamepadA@1' ]
    C = [ 'KeyPad3', 'GamepadB@1' ]
    DPad = [ 'GamepadDPad@1', 'GamepadLeftStick@1' ]
    Down = [ 'Down', 'End' ]
    L = [ 'KeyPad7', 'Insert' ]
    Left = [ 'Left', 'Delete' ]
    R = [ 'KeyPad9', 'PageUp' ]
    Right = [ 'Right', 'PageDown' ]
    Start = [ 'KeyPadEnter', 'GamepadStart@1' ]
    SwitchMode = [ 'KeyPadAdd', 'GamepadLeftThumb@1' ]
    Up = [ 'Up', 'Home' ]
    X = [ 'KeyPad4', 'GamepadLeftBumper@1' ]
    Y = [ 'KeyPad5', 'GamepadY@1' ]
    Z = [ 'KeyPad6', 'GamepadRightBumper@1' ]

    [Input.Port2.ArcadeRacer]
    Sensitivity = 0.5

        [Input.Port2.ArcadeRacer.Binds]
        A = [ 'KeyPad1', 'GamepadX@1' ]
        B = [ 'KeyPad2', 'GamepadA@1' ]
        C = [ 'KeyPad3', 'GamepadB@1' ]
        Down = [ 'Up', 'Home', 'GamepadDpadUp@1', 'GamepadLeftTriggerButton@1' ]
        Start = [ 'KeyPadEnter', 'GamepadStart@1' ]
        Up = [ 'Down', 'End', 'GamepadDpadDown@1', 'GamepadRightTriggerButton@1' ]
        Wheel = [ 'GamepadLeftStickX@1' ]
        WheelLeft = [ 'Left', 'Delete' ]
        WheelRight = [ 'Right', 'PageDown' ]
        X = [ 'KeyPad4', 'GamepadLeftBumper@1' ]
        Y = [ 'KeyPad5', 'GamepadY@1' ]
        Z = [ 'KeyPad6', 'GamepadRightBumper@1' ]

    [Input.Port2.ControlPad.Binds]
    A = [ 'KeyPad1', 'GamepadX@1' ]
    B = [ 'KeyPad2', 'GamepadA@1' ]
    C = [ 'KeyPad3', 'GamepadB@1' ]
    DPad = [ 'GamepadDPad@1', 'GamepadLeftStick@1' ]
    Down = [ 'Down', 'End' ]
    L = [ 'KeyPad7', 'Insert', 'GamepadLeftTriggerButton@1' ]
    Left = [ 'Left', 'Delete' ]
    R = [ 'KeyPad9', 'GamepadRightTriggerButton@1', 'PageUp' ]
    Right = [ 'Right', 'PageDown' ]
    Start = [ 'KeyPadEnter', 'GamepadStart@1' ]
    Up = [ 'Up', 'Home' ]
    X = [ 'KeyPad4', 'GamepadLeftBumper@1' ]
    Y = [ 'KeyPad5', 'GamepadY@1' ]
    Z = [ 'KeyPad6', 'GamepadRightBumper@1' ]

    [Input.Port2.MissionStick.Binds]
    A = [ 'GamepadX@1' ]
    B = [ 'GamepadA@1' ]
    C = [ 'GamepadB@1' ]
    L = [ 'GamepadLeftThumb@1' ]
    MainDown = []
    MainLeft = []
    MainRight = []
    MainStick = [ 'GamepadLeftStick@1', 'GamepadDPad@1' ]
    MainThrottle = [ 'GamepadLeftTrigger@1' ]
    MainThrottleDown = []
    MainThrottleMax = []
    MainThrottleMin = []
    MainThrottleUp = []
    MainUp = []
    R = [ 'GamepadRightThumb@1' ]
    Start = [ 'GamepadStart@1' ]
    SubDown = []
    SubLeft = []
    SubRight = []
    SubStick = [ 'GamepadRightStick@1' ]
    SubThrottle = [ 'GamepadRightTrigger@1' ]
    SubThrottleDown = []
    SubThrottleMax = []
    SubThrottleMin = []
    SubThrottleUp = []
    SubUp = []
    SwitchMode = [ 'GamepadBack@1' ]
    X = [ 'GamepadLeftBumper@1' ]
    Y = [ 'GamepadY@1' ]
    Z = [ 'GamepadRightBumper@1' ]

    [Input.Port2.ShuttleMouse]
    Sensitivity = 4.0
    Speed = 30.0
    SpeedBoostFactor = 2.0

        [Input.Port2.ShuttleMouse.Binds]
        Left = [ 'KeyPad1', 'GamepadA@1' ]
        Middle = [ 'KeyPad2', 'GamepadX@1' ]
        Move = [ 'GamepadDPad@1', 'GamepadLeftStick@1' ]
        MoveDown = [ 'Down', 'End' ]
        MoveLeft = [ 'Left', 'Delete' ]
        MoveRight = [ 'Right', 'PageDown' ]
        MoveUp = [ 'Up', 'Home' ]
        Right = [ 'KeyPad3', 'GamepadB@1' ]
        SpeedBoost = [ 'KeyPad0', 'GamepadLeftBumper@1' ]
        SpeedToggle = [ 'KeyPadPeriod', 'GamepadLeftTriggerButton@1' ]
        Start = [ 'KeyPadEnter', 'GamepadStart@1' ]

    [Input.Port2.VirtuaGun]
    Speed = 200.0
    SpeedBoostFactor = 2.0

        [Input.Port2.VirtuaGun.Binds]
        Down = [ 'Down', 'End' ]
        Left = [ 'Left', 'Delete' ]
        Move = [ 'GamepadDPad@1', 'GamepadLeftStick@1' ]
        Recenter = [ 'KeyPad0', 'GamepadLeftThumb@1' ]
        Reload = [ 'KeyPad2', 'GamepadB@1' ]
        Right = [ 'Right', 'PageDown' ]
        SpeedBoost = [ 'KeyPad3', 'GamepadLeftBumper@1' ]
        SpeedToggle = [ 'KeyPad6', 'GamepadLeftTriggerButton@1' ]
        Start = [ 'KeyPadEnter', 'GamepadStart@1' ]
        Trigger = [ 'KeyPad1', 'GamepadA@1' ]
        Up = [ 'Up', 'Home' ]

        [Input.Port2.VirtuaGun.Crosshair]
        Color = [ 0.0, 0.5, 1.0, 0.87999999523162842 ]
        Radius = 15.0
        Rotation = 45.0
        StrokeColor = [ 0.0, 0.0, 0.0, 1.0 ]
        StrokeThickness = 0.25
        Thickness = 0.33000001311302185

[System]
AutoDetectRegion = true
EmulateSH2Cache = false
InternalBackupRAMImagePath = 'bup-int.bin'
InternalBackupRAMPerGame = false
PreferredRegionOrder = [ 'NorthAmerica', 'EuropePAL', 'Japan', 'AsiaNTSC' ]
SH2ClockFactor = 100
VideoStandard = 'NTSC'

    [System.IPL]
    Override = true
    Path = 'Sega Saturn BIOS (USA).bin'
    Variant = 'Saturn'

    [System.RTC]
    Mode = 'Host'

        [System.RTC.Virtual]
        HardResetStrategy = 'Preserve'
        HardResetTimestamp = 757407600

[Video]
AutoResizeWindow = false
DisplayVideoOutputInWindow = false
DoubleClickToFullScreen = false
ForceAspectRatio = true
ForceIntegerScaling = false
ForcedAspect = 1.3333333333333333
FullScreen = true
ReduceLatency = true
Rotation = 'Normal'
SyncInFullscreenMode = true
SyncInWindowedMode = false
UseFullRefreshRateWithVideoSync = false

    [Video.Enhancements]
    Deinterlace = false
    TransparentMeshes = false

    [Video.FullScreenDisplay]
    Name = ''
    X = 0
    Y = 0

    [Video.FullScreenMode]
    Borderless = true
    Height = 0
    PixelDensity = 0.0
    PixelFormat = 'None'
    RefreshRate = 0.0
    Width = 0

    [Video.SoftwareRenderer]
    ThreadedDeinterlacer = true
    ThreadedVDP1 = true
    ThreadedVDP2 = true