# ============================================================
#  Gaming-Console
#    make             build (optimised)
#    make run         build, then launch from the repo root
#    make DEBUG=1     build with sanitizers into build-debug/
#    make clean       remove build output
#    make -j4         parallel build
# ============================================================

CC ?= gcc

# --- flags --------------------------------------------------
# gnu11, not c11: strict ISO hides POSIX functions like realpath,
# which retro_bridge.c needs.
STD  := -std=gnu11
WARN := -Wall -Wextra -Wno-unused-parameter
# Includes mix bare ("var.h") and prefixed ("ui/ui.h") forms,
# so all four directories have to be searchable.
INC  := -Isrc -Isrc/ui -Isrc/play -Isrc/libretro

RAYLIB_CFLAGS := $(shell pkg-config --cflags raylib 2>/dev/null)
RAYLIB_LIBS := -L/usr/local/lib -lraylib -lGL -lX11

# --- debug vs release ---------------------------------------
# Separate output dirs so the two never mix stale objects.
ifdef DEBUG
  BUILD  := build-debug
  TARGET := gaming-console-debug
  OPT    := -O0 -g3
  SANI   := -fsanitize=address,undefined -fno-omit-frame-pointer
else
  BUILD  := build
  TARGET := gaming-console
  OPT    := -O2 -g
  SANI   :=
endif

CFLAGS  := $(STD) $(WARN) $(OPT) $(SANI) $(INC) $(RAYLIB_CFLAGS)
LDFLAGS := $(SANI)
LDLIBS  := $(RAYLIB_LIBS) -lm -lpthread -ldl -lrt

# --- sources ------------------------------------------------
SRCS := \
  src/main.c \
  src/var.c \
  src/games.c \
  src/categories.c \
  src/states.c \
  src/controller.c \
  src/ui/ui.c \
  src/ui/uipause.c \
  src/ui/theme.c \
  src/ui/brightness.c \
  src/ui/diagnostics.c \
  src/ui/erase.c \
  src/play/play.c \
  src/play/playpause.c \
  src/libretro/retro_bridge.c

OBJS := $(SRCS:%.c=$(BUILD)/%.o)
DEPS := $(OBJS:.o=.d)

# --- rules --------------------------------------------------
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@ $(LDLIBS)

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Assets resolve relative to the working directory,
# so always launch from the repo root.
run: $(TARGET)
	./$(TARGET)

clean:
	rm -rf build build-debug gaming-console gaming-console-debug

# Header dependencies generated by -MMD (absent on a cold build, hence '-')
-include $(DEPS)

.PHONY: all run clean