#ifndef UIPAUSE_CONFIG_H
#define UIPAUSE_CONFIG_H

//Thickness for the uipause menu
#define THICKNESS_UIPAUSE (Var_GetMonitorHeight() / 500.0f)
//Macros for drawing the menu background
#define UIPAUSE_RECT_X (CENTER_X - UIPAUSE_RECT_W / 2)
#define UIPAUSE_RECT_Y (Var_GetMonitorHeight() * (1.0f / 2) - UIPAUSE_RECT_H / 2)
#define UIPAUSE_RECT_W (Var_GetMonitorWidth() * (2.0f / 5))
#define UIPAUSE_RECT_H (Var_GetMonitorHeight() * (2.0f / 5))
#define UIPAUSE_ROUND 0.025f
#define UIPAUSE_SEGMENTS 15
//Macros for drawing the individual options on the menu
#define UIPAUSE_TXT_SPACING_Y (Var_GetMonitorHeight() / 30.0f)
#define UIPAUSE_TITLE "[OPTIONS]"
#define UIPAUSE_TITLE_SIZE (Var_GetMonitorWidth() / 40.0f)
#define UIPAUSE_TITLE_SPACE (Var_GetMonitorWidth() / 400.0f)
#define UIPAUSE_TITLE_X (CENTER_X - titleSize.x / 2)
#define UIPAUSE_TITLE_Y (UIPAUSE_RECT_Y + UIPAUSE_TXT_SPACING_Y - titleSize.y / 2)
#define UIPAUSE_VIEW_LIST "View games/consoles list"
#define UIPAUSE_VIEW_LIST_SIZE (UIPAUSE_TITLE_SIZE * (3.0f / 4))
#define UIPAUSE_VIEW_LIST_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_VIEW_LIST_Y (UIPAUSE_TITLE_Y + titleSize.y + UIPAUSE_TXT_SPACING_Y -listSize.y / 2)
#define UIPAUSE_BRIGHTNESS "Adjust brightness"
#define UIPAUSE_BRIGHTNESS_SIZE (UIPAUSE_TITLE_SIZE * (3.0f / 4))
#define UIPAUSE_BRIGHTNESS_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_BRIGHTNESS_Y (UIPAUSE_VIEW_LIST_Y + listSize.y + UIPAUSE_TXT_SPACING_Y * (7.0f / 6)  - brightnessSize.y / 2)
#define UIPAUSE_THEME "Select theme"
#define UIPAUSE_THEME_SIZE (UIPAUSE_TITLE_SIZE * (3.0f / 4))
#define UIPAUSE_THEME_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_THEME_Y (UIPAUSE_BRIGHTNESS_Y + brightnessSize.y + UIPAUSE_TXT_SPACING_Y * (7.0f / 6) - themeSize.y / 2)
#define UIPAUSE_DISPLAY_DIAGNOSTICS "Display diagnostics"
#define UIPAUSE_HIDE_DIAGNOSTICS "Hide diagnostics"
#define UIPAUSE_DISPLAY_DIAGNOSTICS_SIZE (UIPAUSE_TITLE_SIZE * (3.0f / 4))
#define UIPAUSE_DISPLAY_DIAGNOSTICS_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_DISPLAY_DIAGNOSTICS_Y (UIPAUSE_THEME_Y + themeSize.y + UIPAUSE_TXT_SPACING_Y * (7.0f / 6) - displayDiagSize.y / 2)
#define UIPAUSE_DIAGNOSTICS "View diagnostics menu"
#define UIPAUSE_MAIN "View main menu"
#define UIPAUSE_DIAGNOSTICS_SIZE (UIPAUSE_TITLE_SIZE * (3.0f / 4))
#define UIPAUSE_DIAGNOSTICS_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_DIAGNOSTICS_Y (UIPAUSE_DISPLAY_DIAGNOSTICS_Y + displayDiagSize.y + UIPAUSE_TXT_SPACING_Y * (7.0f / 6) - diagSize.y / 2)
#define UIPAUSE_SELECT "[A/ENTER] SELECT"
#define UIPAUSE_SELECT_SIZE (UIPAUSE_TITLE_SIZE * (1.0f / 2))
#define UIPAUSE_SELECT_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y / 2.0f)
#define UIPAUSE_SELECT_Y (UIPAUSE_RECT_Y + UIPAUSE_RECT_H - UIPAUSE_TXT_SPACING_Y / 2 - selectSize.y)
#define UIPAUSE_BACK "[B/ESC] BACK"
#define UIPAUSE_BACK_SIZE (UIPAUSE_TITLE_SIZE * (1.0f / 2))
#define UIPAUSE_BACK_X (UIPAUSE_RECT_X + UIPAUSE_RECT_W - UIPAUSE_TXT_SPACING_Y / 2.0f - backSize.x)
#define UIPAUSE_BACK_Y (UIPAUSE_RECT_Y + UIPAUSE_RECT_H - UIPAUSE_TXT_SPACING_Y / 2 - backSize.y)
#define UIPAUSE_SELECT_RECT_X (UIPAUSE_RECT_X + UIPAUSE_TXT_SPACING_Y / 2)
#define UIPAUSE_SELECT_RECT_W (UIPAUSE_RECT_W - UIPAUSE_TXT_SPACING_Y)
#define UIPAUSE_SELECT_RECT_H (listSize.y + UIPAUSE_TXT_SPACING_Y / 4)
#define UIPAUSE_VIEW_LIST_RECT_Y (UIPAUSE_VIEW_LIST_Y - UIPAUSE_TXT_SPACING_Y / 16)
#define UIPAUSE_BRIGHTNESS_RECT_Y (UIPAUSE_BRIGHTNESS_Y - UIPAUSE_TXT_SPACING_Y / 16)
#define UIPAUSE_THEME_RECT_Y (UIPAUSE_THEME_Y - UIPAUSE_TXT_SPACING_Y / 16)
#define UIPAUSE_DISPLAY_DIAGNOSTICS_RECT_Y (UIPAUSE_DISPLAY_DIAGNOSTICS_Y - UIPAUSE_TXT_SPACING_Y / 16)
#define UIPAUSE_DIAGNOSTICS_RECT_Y (UIPAUSE_DIAGNOSTICS_Y - UIPAUSE_TXT_SPACING_Y / 16)

#endif