#ifndef PLAYPAUSE_CONFIG_H
#define PLAYPAUSE_CONFIG_H

#define MAX_TIME_ELAPSED_PLAYPAUSE 1000000
#define THRESHOLD_TIME_ELAPSED_PLAYPAUSE 0.25f
#define PLAYPAUSE_STR_LEN 10
#define PLAYPAUSE_STR_LEN2 13
#define PLAYPAUSE_STR_LEN3 15

#define PLAYPAUSE_LINE_THICK (Var_GetMonitorHeight() / 500.0f)

#define PLAYPAUSE_RECT_X (CENTER_X - PLAYPAUSE_RECT_W / 2)
#define PLAYPAUSE_RECT_Y (Var_GetMonitorHeight() * (1.0f / 2) - PLAYPAUSE_RECT_H / 2)
#define PLAYPAUSE_RECT_W (Var_GetMonitorWidth() * (2.0f / 5))
#define PLAYPAUSE_RECT_H (Var_GetMonitorHeight() / 9.0f * 4)
#define PLAYPAUSE_ROUND 0.025f
#define PLAYPAUSE_SEGMENTS 15

#define PLAYPAUSE_SPACING_Y (Var_GetMonitorHeight() / 30.0f)
#define PLAYPAUSE_TITLE "[PAUSED]"
#define PLAYPAUSE_TITLE_SIZE (Var_GetMonitorWidth() / 50.0f)
#define PLAYPAUSE_SPACE (Var_GetMonitorWidth() / 400.0f)
#define PLAYPAUSE_TITLE_X (CENTER_X - titleSize.x / 2)
#define PLAYPAUSE_TITLE_Y (PLAYPAUSE_RECT_Y + PLAYPAUSE_SPACING_Y - titleSize.y / 2)

#define PLAYPAUSE_SIZE (PLAYPAUSE_TITLE_SIZE * (5.0f / 6))
#define PLAYPAUSE_X (PLAYPAUSE_RECT_X + PLAYPAUSE_SPACING_Y * 5.0f / 4)
#define RESUME_TXT "Resume game"
#define RESUME_Y (PLAYPAUSE_TITLE_Y + titleSize.y + PLAYPAUSE_SPACING_Y - resumeSize.y / 2)
#define RESTART_TXT "Restart game"
#define RESTART_Y (RESUME_Y + PLAYPAUSE_SPACING_Y * (5.0f / 4) + resumeSize.y / 2)
#define CONTROLS_TXT "View controls"
#define CONTROLS_Y (RESTART_Y + PLAYPAUSE_SPACING_Y * (5.0f / 4) + resumeSize.y / 2)
#define DISPLAY_DIAGNOSTICS_TXT "Display diagnostics"
#define HIDE_DIAGNOSTICS_TXT "Hide diagnostics"
#define DIAGNOSTICS_Y (CONTROLS_Y + PLAYPAUSE_SPACING_Y * (5.0f / 4) + resumeSize.y / 2)
#define EXIT_TXT "Exit game"
#define EXIT_Y (DIAGNOSTICS_Y + PLAYPAUSE_SPACING_Y * (5.0f / 4) + resumeSize.y / 2)
#define POWER_OFF_TXT "Power off"
#define POWER_OFF_X (PLAYPAUSE_X)
#define POWER_OFF_Y (EXIT_Y + resumeSize.y + PLAYPAUSE_SPACING_Y * (5.0f / 4) - resumeSize.y / 2)

#define PLAYPAUSE_SELECT_RECT_X (PLAYPAUSE_RECT_X + PLAYPAUSE_SPACING_Y / 4.0f * 3)
#define PLAYPAUSE_SELECT_RECT_H (resumeSize.y + PLAYPAUSE_SPACING_Y / 3)
#define PLAYPAUSE_SELECT_RECT_W (PLAYPAUSE_RECT_W - PLAYPAUSE_SPACING_Y / 4.0f * 6)
#define PLAYPAUSE_RESUME_RECT_Y (RESUME_Y - PLAYPAUSE_SPACING_Y / 12)
#define PLAYPAUSE_RESTART_RECT_Y (RESTART_Y - PLAYPAUSE_SPACING_Y / 12)
#define PLAYPAUSE_CONTROLS_RECT_Y (CONTROLS_Y - PLAYPAUSE_SPACING_Y / 12)
#define PLAYPAUSE_DIAGNOSTICS_RECT_Y (DIAGNOSTICS_Y - PLAYPAUSE_SPACING_Y / 12)
#define PLAYPAUSE_EXIT_RECT_Y (EXIT_Y - PLAYPAUSE_SPACING_Y / 12)
#define PLAYPAUSE_POWER_OFF_RECT_Y (POWER_OFF_Y - PLAYPAUSE_SPACING_Y / 12)

#define SELECT_TXT "[A/ENTER] SELECT"
#define SELECT_SIZE (PLAYPAUSE_TITLE_SIZE * (1.0f / 2))
#define SELECT_X (PLAYPAUSE_RECT_X + PLAYPAUSE_SPACING_Y / 2.0f)
#define SELECT_Y (PLAYPAUSE_RECT_Y + PLAYPAUSE_RECT_H - PLAYPAUSE_SPACING_Y / 2 - selectSize.y)

#define BACK_TXT "[B/ESC] BACK"
#define BACK_SIZE (PLAYPAUSE_TITLE_SIZE * (1.0f / 2))
#define BACK_X (PLAYPAUSE_RECT_X + PLAYPAUSE_RECT_W - PLAYPAUSE_SPACING_Y / 2.0f - backSize.x)
#define BACK_Y (PLAYPAUSE_RECT_Y + PLAYPAUSE_RECT_H - PLAYPAUSE_SPACING_Y / 2 - backSize.y)

#define PLAYPAUSE_CONTROL_BACK "[B/ESC] BACK"
#define PLAYPAUSE_CONTROL_BACK_SIZE (PLAYPAUSE_TITLE_SIZE * (1.0f / 2))
#define PLAYPAUSE_CONTROL_BACK_X (PLAYPAUSE_KEYBOARD_X + PLAYPAUSE_KEYBOARD_W - PLAYPAUSE_SPACING_Y / 2.0f - backSize.x)
#define PLAYPAUSE_CONTROL_BACK_Y (PLAYPAUSE_KEYBOARD_Y + PLAYPAUSE_KEYBOARD_H - PLAYPAUSE_SPACING_Y / 2.0f - backSize.y)




#endif