#include "playpause.h"
#include "playpause_config.h"
#include "controller.h"
#include "raylib.h"
#include "config.h"
#include "games.h"
#include "var.h"
#include <stdio.h>
#include <string.h>
#include "ui/ui.h"

//Current state of the pause screen
static PlayPauseState currentPlayPauseState;
//Controller/keyboard and mouse images
static Texture2D controlsImg;
static Texture2D keyImg;
static Texture2D mouseImg;
static Texture2D arrowsImg;
//Variable to keep track of if controls are being displayed
static bool displayControls;
//Time spent on current section
static float playPauseTimeElapsed;


//Update the time elapsed on one section of the paused screen
static void PlayPause_UpdateTime(void) {
    playPauseTimeElapsed += GetFrameTime();
    //If the variable is getting too big, bring it back down
    if (playPauseTimeElapsed > MAX_TIME_ELAPSED) {
        playPauseTimeElapsed = THRESHOLD_TIME_ELAPSED;
    }
}

//Draw specific control with normal size
static void PlayPause_DrawControlTxt(const char* control, float x, float y, float font_size) {
    char txt[PLAYPAUSE_STR_LEN];
    snprintf(txt, sizeof(txt), "%s", control);
    Vector2 size = MeasureTextEx(Var_GetFontBold(), txt, font_size, PLAYPAUSE_CONTROL_SPACE);
    Vector2 position = {x - size.x / 2.0f, y - size.y / 2.0f};
    DrawTextEx(Var_GetFontBold(), txt, position, font_size, PLAYPAUSE_CONTROL_SPACE, BLACK);
}

//Draw box and line for the keyboard and mouse controls
static void PlayPause_DrawKeyBox(float lineStartX, float lineEndX, float lineStartY, float lineEndY, float boxX, float boxY) {
    Vector2 origin = {0.0f, 0.0f};
    Vector2 start = {lineStartX, lineStartY};
    Vector2 end = {lineEndX, lineEndY};
    DrawLineEx(start, end, PLAYPAUSE_KEY_THICKNESS, GRAY);
    Rectangle rect = {boxX, boxY, PLAYPAUSE_KEY_REC_W, PLAYPAUSE_KEY_REC_H};
    DrawRectanglePro(rect, origin, 0.0f, GRAY);
}

//Draw the controls for the game
static void PlayPause_DrawControls(const game_t* game) {
    //Draw controller image
    Rectangle sourceRect_Controller = {0.0f, 0.0f, (float)controlsImg.width, (float)controlsImg.height};
    Rectangle destRect_Controller = {PLAYPAUSE_CONTROLLER_X, PLAYPAUSE_CONTROLLER_Y, PLAYPAUSE_CONTROLLER_W, PLAYPAUSE_CONTROLLER_H};
    Vector2 origin = {0.0f, 0.0f};
    DrawTexturePro(controlsImg, sourceRect_Controller, destRect_Controller, origin, 0.0f, WHITE);
    //Draw keyboard rectangle
    Rectangle rect = {PLAYPAUSE_KEYBOARD_X, PLAYPAUSE_KEYBOARD_Y, PLAYPAUSE_KEYBOARD_W, PLAYPAUSE_KEYBOARD_H};
    DrawRectanglePro(rect, origin, 0.0f, WHITE);
    Vector2 middleLineStart = {PLAYPAUSE_KEYBOARD_X, PLAYPAUSE_CONTROLLER_Y};
    Vector2 middleLineEnd = {PLAYPAUSE_KEYBOARD_X, PLAYPAUSE_CONTROLLER_Y + PLAYPAUSE_CONTROLLER_H};
    DrawLineEx(middleLineStart, middleLineEnd, PLAYPAUSE_CONTROL_OUTLINE_THICKNESS, GRAY);
    //Draw circles and rectangles for backgrounds of each xbox control
    DrawCircle(PLAYPAUSE_RIGHT_FACE_DOWN_X, PLAYPAUSE_RIGHT_FACE_DOWN_Y, PLAYPAUSE_CONTROL_RADIUS, GRAY);
    DrawCircle(PLAYPAUSE_RIGHT_FACE_UP_X, PLAYPAUSE_RIGHT_FACE_UP_Y, PLAYPAUSE_CONTROL_RADIUS, GRAY);
    DrawCircle(PLAYPAUSE_RIGHT_FACE_LEFT_X, PLAYPAUSE_RIGHT_FACE_LEFT_Y, PLAYPAUSE_CONTROL_RADIUS, GRAY);
    DrawCircle(PLAYPAUSE_RIGHT_FACE_RIGHT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_Y, PLAYPAUSE_CONTROL_RADIUS, GRAY);
    DrawRectangle(PLAYPAUSE_HOME_RECT_X, PLAYPAUSE_HOME_RECT_Y, PLAYPAUSE_HOME_RECT_W, PLAYPAUSE_HOME_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_DPAD_RECT_X, PLAYPAUSE_DPAD_RECT_Y, PLAYPAUSE_DPAD_RECT_W, PLAYPAUSE_DPAD_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_RS_RECT_X, PLAYPAUSE_RS_RECT_Y, PLAYPAUSE_RS_RECT_W, PLAYPAUSE_RS_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_BACK_RECT_X, PLAYPAUSE_BACK_RECT_Y, PLAYPAUSE_BACK_RECT_W, PLAYPAUSE_BACK_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_START_RECT_X, PLAYPAUSE_START_RECT_Y, PLAYPAUSE_START_RECT_W, PLAYPAUSE_START_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_LT_RECT_X, PLAYPAUSE_LT_RECT_Y, PLAYPAUSE_LT_RECT_W, PLAYPAUSE_LT_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_RT_RECT_X, PLAYPAUSE_RT_RECT_Y, PLAYPAUSE_RT_RECT_W, PLAYPAUSE_RT_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_LB_RECT_X, PLAYPAUSE_LB_RECT_Y, PLAYPAUSE_LB_RECT_W, PLAYPAUSE_LB_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_RB_RECT_X, PLAYPAUSE_RB_RECT_Y, PLAYPAUSE_RB_RECT_W, PLAYPAUSE_RB_RECT_H, GRAY);
    DrawRectangle(PLAYPAUSE_LS_RECT_X, PLAYPAUSE_LS_RECT_Y, PLAYPAUSE_LS_RECT_W, PLAYPAUSE_LS_RECT_H, GRAY);
    //Keyboard controls
    Rectangle sourceRect_Key = {0.0f, 0.0f, (float)keyImg.width, (float)keyImg.height};
    Rectangle destRect_Key = {PLAYPAUSE_KEY_X, PLAYPAUSE_KEY_Y, PLAYPAUSE_KEY_W, PLAYPAUSE_KEY_H};
    DrawTexturePro(keyImg, sourceRect_Key, destRect_Key, origin, 0.0f, WHITE);
    Rectangle sourceRect_Mouse = {0.0f, 0.0f, (float)mouseImg.width, (float)mouseImg.height};
    Rectangle destRect_Mouse = {PLAYPAUSE_MOUSE_X, PLAYPAUSE_MOUSE_Y, PLAYPAUSE_MOUSE_W, PLAYPAUSE_MOUSE_H};
    DrawTexturePro(mouseImg, sourceRect_Mouse, destRect_Mouse, origin, 0.0f, WHITE);
    Rectangle sourceRect_Arrow = {0.0f, 0.0f, (float)arrowsImg.width, (float)arrowsImg.height};
    Rectangle destRect_Arrow = {PLAYPAUSE_ARROWS_X, PLAYPAUSE_ARROWS_Y, PLAYPAUSE_ARROWS_W, PLAYPAUSE_ARROWS_H};
    DrawTexturePro(arrowsImg, sourceRect_Arrow, destRect_Arrow, origin, 0.0f, WHITE);
    //1st keyboard row
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_TAB_LINE_X, PLAYPAUSE_KEY_TAB_LINE_X, PLAYPAUSE_KEY_TAB_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_TAB_X, PLAYPAUSE_KEY_TAB_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_Q_LINE_X, PLAYPAUSE_KEY_Q_LINE_X, PLAYPAUSE_KEY_Q_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP2,
                        PLAYPAUSE_KEY_Q_X, PLAYPAUSE_KEY_Q_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_W_LINE_X, PLAYPAUSE_KEY_W_LINE_X, PLAYPAUSE_KEY_W_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_W_X, PLAYPAUSE_KEY_W_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_E_LINE_X, PLAYPAUSE_KEY_E_LINE_X, PLAYPAUSE_KEY_E_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP2,
                        PLAYPAUSE_KEY_E_X, PLAYPAUSE_KEY_E_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_U_LINE_X, PLAYPAUSE_KEY_U_LINE_X, PLAYPAUSE_KEY_U_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_U_X, PLAYPAUSE_KEY_U_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_I_LINE_X, PLAYPAUSE_KEY_I_LINE_X, PLAYPAUSE_KEY_I_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP2,
                        PLAYPAUSE_KEY_I_X, PLAYPAUSE_KEY_I_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_O_LINE_X, PLAYPAUSE_KEY_O_LINE_X, PLAYPAUSE_KEY_O_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_O_X, PLAYPAUSE_KEY_O_Y);
    //2nd keyboard row
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_A_LINE_X, PLAYPAUSE_KEY_A_LINE_X, PLAYPAUSE_KEY_A_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM2,
                        PLAYPAUSE_KEY_A_X, PLAYPAUSE_KEY_A_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_S_LINE_X, PLAYPAUSE_KEY_S_LINE_X, PLAYPAUSE_KEY_S_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_S_X, PLAYPAUSE_KEY_S_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_D_LINE_X, PLAYPAUSE_KEY_D_LINE_X, PLAYPAUSE_KEY_D_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM2,
                        PLAYPAUSE_KEY_D_X, PLAYPAUSE_KEY_D_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_F_LINE_X, PLAYPAUSE_KEY_F_LINE_X, PLAYPAUSE_KEY_F_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_F_X, PLAYPAUSE_KEY_F_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_J_LINE_X, PLAYPAUSE_KEY_J_LINE_X, PLAYPAUSE_KEY_J_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM2,
                        PLAYPAUSE_KEY_J_X, PLAYPAUSE_KEY_J_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_K_LINE_X, PLAYPAUSE_KEY_K_LINE_X, PLAYPAUSE_KEY_K_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_K_X, PLAYPAUSE_KEY_K_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_L_LINE_X, PLAYPAUSE_KEY_L_LINE_X, PLAYPAUSE_KEY_L_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM2,
                        PLAYPAUSE_KEY_L_X, PLAYPAUSE_KEY_L_Y);
    //Other keys
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_ENTER_LINE_X, PLAYPAUSE_KEY_ENTER_LINE_X, PLAYPAUSE_KEY_ENTER_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_ENTER_X, PLAYPAUSE_KEY_ENTER_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_RSHIFT_LINE_X, PLAYPAUSE_KEY_RSHIFT_LINE_X, PLAYPAUSE_KEY_RSHIFT_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_RSHIFT_X, PLAYPAUSE_KEY_RSHIFT_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_LSHIFT_LINE_X, PLAYPAUSE_KEY_LSHIFT_LINE_X, PLAYPAUSE_KEY_LSHIFT_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_LSHIFT_X, PLAYPAUSE_KEY_LSHIFT_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_SPACE_LINE_X, PLAYPAUSE_KEY_SPACE_LINE_X, PLAYPAUSE_KEY_SPACE_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM2,
                        PLAYPAUSE_KEY_SPACE_X, PLAYPAUSE_KEY_SPACE_Y);
    //Mouse
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_MOUSE_LINE_X, PLAYPAUSE_KEY_MOUSE_LINE_X, PLAYPAUSE_KEY_MOUSE_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_TOP1,
                        PLAYPAUSE_KEY_MOUSE_X, PLAYPAUSE_KEY_MOUSE_Y);
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_LCLICK_LINE_X, PLAYPAUSE_KEY_LCLICK_LINE_X, PLAYPAUSE_KEY_LCLICK_LINE_Y_START, PLAYPAUSE_KEY_LINE_END_BOTTOM1,
                        PLAYPAUSE_KEY_LCLICK_X, PLAYPAUSE_KEY_LCLICK_Y);
    //Arrows
    PlayPause_DrawKeyBox(PLAYPAUSE_KEY_ARROWS_LINE_X1, PLAYPAUSE_KEY_ARROWS_LINE_X2, PLAYPAUSE_KEY_ARROWS_LINE_Y, PLAYPAUSE_KEY_ARROWS_LINE_Y,
                        PLAYPAUSE_KEY_ARROWS_REC_X, PLAYPAUSE_KEY_ARROWS_REC_Y);
    //Common home control for all consoles
    PlayPause_DrawControlTxt("PAUSE", PLAYPAUSE_HOME_TXT_X, PLAYPAUSE_HOME_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    //Draw the controls depending on the console
    if (strcmp(game->console, "Sega Genesis") == 0 || strcmp(game->console, "Sega CD") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("MODE", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("MODE", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_RIGHT_FACE_LEFT_TXT_X, PLAYPAUSE_RIGHT_FACE_LEFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_KEY_I_TXT_X, PLAYPAUSE_KEY_I_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Y", PLAYPAUSE_RIGHT_FACE_UP_TXT_X, PLAYPAUSE_RIGHT_FACE_UP_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Y", PLAYPAUSE_KEY_L_TXT_X, PLAYPAUSE_KEY_L_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Z", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Z", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Sega Game Gear") == 0 || strcmp(game->console, "Sega Master System") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("1", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("1", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("2", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("2", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "TurboGrafx-16") == 0 || strcmp(game->console, "TurboGrafx-CD") == 0) {
        PlayPause_DrawControlTxt("RUN", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("RUN", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("I", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("I", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("II", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("II", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Neo Geo Pocket Color") == 0) {
        PlayPause_DrawControlTxt("OPTION", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("OPTION", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Nintendo Entertainment System") == 0
             || strcmp(game->console, "Game Boy Color") == 0
             || strcmp(game->console, "Atari Lynx") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Super Nintendo Entertainment System") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Y", PLAYPAUSE_RIGHT_FACE_LEFT_TXT_X, PLAYPAUSE_RIGHT_FACE_LEFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Y", PLAYPAUSE_KEY_I_TXT_X, PLAYPAUSE_KEY_I_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_RIGHT_FACE_UP_TXT_X, PLAYPAUSE_RIGHT_FACE_UP_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_KEY_L_TXT_X, PLAYPAUSE_KEY_L_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Game Boy Advance") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Sony PlayStation") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("X", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("O", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("O", PLAYPAUSE_KEY_L_TXT_X, PLAYPAUSE_KEY_L_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SELECT", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SQR", PLAYPAUSE_RIGHT_FACE_LEFT_TXT_X, PLAYPAUSE_RIGHT_FACE_LEFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SQR", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("TRI", PLAYPAUSE_RIGHT_FACE_UP_TXT_X, PLAYPAUSE_RIGHT_FACE_UP_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("TRI", PLAYPAUSE_KEY_I_TXT_X, PLAYPAUSE_KEY_I_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L1", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L1", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R1", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R1", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L2", PLAYPAUSE_LT_TXT_X, PLAYPAUSE_LT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L2", PLAYPAUSE_KEY_Q_TXT_X, PLAYPAUSE_KEY_Q_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R2", PLAYPAUSE_RT_TXT_X, PLAYPAUSE_RT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R2", PLAYPAUSE_KEY_E_TXT_X, PLAYPAUSE_KEY_E_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Nintendo 64") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("B", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("A", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_KEY_ARROWS_TXT_X, PLAYPAUSE_KEY_ARROWS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("L", PLAYPAUSE_KEY_Q_TXT_X, PLAYPAUSE_KEY_Q_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("R", PLAYPAUSE_KEY_E_TXT_X, PLAYPAUSE_KEY_E_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Z", PLAYPAUSE_LT_TXT_X, PLAYPAUSE_LT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("Z", PLAYPAUSE_KEY_SPACE_TXT_X, PLAYPAUSE_KEY_SPACE_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_RS_TXT_X, PLAYPAUSE_RS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_KEY_I_TXT_X, PLAYPAUSE_KEY_I_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("C", PLAYPAUSE_KEY_L_TXT_X, PLAYPAUSE_KEY_L_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "Arcade") == 0) {
        PlayPause_DrawControlTxt("START", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("START", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("1", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("1", PLAYPAUSE_KEY_K_TXT_X, PLAYPAUSE_KEY_K_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("2", PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X, PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("2", PLAYPAUSE_KEY_L_TXT_X, PLAYPAUSE_KEY_L_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("STICK", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("COIN", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("COIN", PLAYPAUSE_KEY_RSHIFT_TXT_X, PLAYPAUSE_KEY_RSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("3", PLAYPAUSE_RIGHT_FACE_LEFT_TXT_X, PLAYPAUSE_RIGHT_FACE_LEFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("3", PLAYPAUSE_KEY_J_TXT_X, PLAYPAUSE_KEY_J_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("4", PLAYPAUSE_RIGHT_FACE_UP_TXT_X, PLAYPAUSE_RIGHT_FACE_UP_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("4", PLAYPAUSE_KEY_I_TXT_X, PLAYPAUSE_KEY_I_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("5", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("5", PLAYPAUSE_KEY_U_TXT_X, PLAYPAUSE_KEY_U_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("6", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("6", PLAYPAUSE_KEY_O_TXT_X, PLAYPAUSE_KEY_O_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    else if (strcmp(game->console, "PC") == 0) {
        PlayPause_DrawControlTxt("ENTER", PLAYPAUSE_START_TXT_X, PLAYPAUSE_START_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("ENTER", PLAYPAUSE_KEY_ENTER_TXT_X, PLAYPAUSE_KEY_ENTER_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("USE", PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X, PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("USE", PLAYPAUSE_KEY_SPACE_TXT_X, PLAYPAUSE_KEY_SPACE_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("MOVE/RUN", PLAYPAUSE_LS_TXT_X, PLAYPAUSE_LS_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM1);
        PlayPause_DrawControlTxt("STRAFE", PLAYPAUSE_KEY_A_TXT_X, PLAYPAUSE_KEY_A_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM1);
        PlayPause_DrawControlTxt("MOVE", PLAYPAUSE_KEY_S_TXT_X, PLAYPAUSE_KEY_S_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM1);
        PlayPause_DrawControlTxt("STRAFE", PLAYPAUSE_KEY_D_TXT_X, PLAYPAUSE_KEY_D_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM1);
        PlayPause_DrawControlTxt("MOVE", PLAYPAUSE_KEY_W_TXT_X, PLAYPAUSE_KEY_W_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM1);
        PlayPause_DrawControlTxt("D-PAD", PLAYPAUSE_DPAD_TXT_X, PLAYPAUSE_DPAD_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("RUN", PLAYPAUSE_KEY_LSHIFT_TXT_X, PLAYPAUSE_KEY_LSHIFT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("MAP", PLAYPAUSE_BACK_TXT_X, PLAYPAUSE_BACK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("MAP", PLAYPAUSE_KEY_TAB_TXT_X, PLAYPAUSE_KEY_TAB_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("FIRE", PLAYPAUSE_RT_TXT_X, PLAYPAUSE_RT_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("FIRE", PLAYPAUSE_KEY_LCLICK_TXT_X, PLAYPAUSE_KEY_LCLICK_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("FIRE", PLAYPAUSE_KEY_F_TXT_X, PLAYPAUSE_KEY_F_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("SWITCH GUNS", PLAYPAUSE_LB_TXT_X, PLAYPAUSE_LB_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM2);
        PlayPause_DrawControlTxt("SWITCH GUNS", PLAYPAUSE_KEY_Q_TXT_X, PLAYPAUSE_KEY_Q_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM2);
        PlayPause_DrawControlTxt("SWITCH GUNS", PLAYPAUSE_RB_TXT_X, PLAYPAUSE_RB_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM2);
        PlayPause_DrawControlTxt("SWITCH GUNS", PLAYPAUSE_KEY_E_TXT_X, PLAYPAUSE_KEY_E_TXT_Y, PLAYPAUSE_CONTROL_SIZE_DOOM2);
        PlayPause_DrawControlTxt("TURN", PLAYPAUSE_RS_TXT_X, PLAYPAUSE_RS_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
        PlayPause_DrawControlTxt("TURN", PLAYPAUSE_KEY_MOUSE_TXT_X, PLAYPAUSE_KEY_MOUSE_TXT_Y, PLAYPAUSE_CONTROL_SIZE);
    }
    //Draw back text
    Vector2 backSize = MeasureTextEx(Var_GetFontRegular(), PLAYPAUSE_CONTROL_BACK, PLAYPAUSE_CONTROL_SIZE, PLAYPAUSE_CONTROL_SPACE);
    Vector2 back = {PLAYPAUSE_CONTROL_BACK_X, PLAYPAUSE_CONTROL_BACK_Y};
    DrawTextEx(Var_GetFontRegular(), PLAYPAUSE_CONTROL_BACK, back, PLAYPAUSE_CONTROL_SIZE, PLAYPAUSE_CONTROL_SPACE, Fade(Var_GetColor2(), Var_GetAlphaSelect()));
    //Draw outline
    Rectangle outline = {PLAYPAUSE_CONTROLLER_X, PLAYPAUSE_CONTROLLER_Y, PLAYPAUSE_CONTROLLER_W * 2, PLAYPAUSE_CONTROLLER_H};
    DrawRectangleLinesEx(outline, PLAYPAUSE_CONTROL_OUTLINE_THICKNESS, GRAY);
}

//Draw the pause screen
static void PlayPause_Draw(void) {
    //Draw whole section
    Rectangle rectSection = {
        PLAYPAUSE_RECT_X,
        PLAYPAUSE_RECT_Y,
        PLAYPAUSE_RECT_W,
        PLAYPAUSE_RECT_H};
    DrawRectangleRounded(rectSection, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, Var_GetColor2());
    DrawRectangleRoundedLinesEx(rectSection, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    //Draw title
    Vector2 titleSize = MeasureTextEx(Var_GetFontBold(), PLAYPAUSE_TITLE, PLAYPAUSE_TITLE_SIZE, PLAYPAUSE_SPACE);
    Vector2 title = {PLAYPAUSE_TITLE_X, PLAYPAUSE_TITLE_Y};
    DrawTextEx(Var_GetFontBold(), PLAYPAUSE_TITLE, title, PLAYPAUSE_TITLE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw resume
    Vector2 resumeSize = MeasureTextEx(Var_GetFontRegular(), RESUME_TXT, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE);
    Vector2 resume = {PLAYPAUSE_X, RESUME_Y};
    Rectangle rectResume = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_RESUME_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectResume, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    DrawTextEx(Var_GetFontRegular(), RESUME_TXT, resume, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw restart
    Vector2 restart = {PLAYPAUSE_X, RESTART_Y};
    Rectangle rectRestart = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_RESTART_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectRestart, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    DrawTextEx(Var_GetFontRegular(), RESTART_TXT, restart, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw controls
    Vector2 controls = {PLAYPAUSE_X, CONTROLS_Y};
    Rectangle rectControls = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_CONTROLS_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectControls, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    DrawTextEx(Var_GetFontRegular(), CONTROLS_TXT, controls, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw display/hide diagnostics
    Vector2 diagnostics = {PLAYPAUSE_X, DIAGNOSTICS_Y};
    Rectangle rectDiag = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_DIAGNOSTICS_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectDiag, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    const char *diagTxt;
    //Set the text depending on if diagnostics are already being displayed
    if (Var_GetDiag()) {
        diagTxt = HIDE_DIAGNOSTICS_TXT;
    }
    else {
        diagTxt = DISPLAY_DIAGNOSTICS_TXT;
    }
    DrawTextEx(Var_GetFontRegular(), diagTxt, diagnostics, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw exit
    Vector2 exit = {PLAYPAUSE_X, EXIT_Y};
    Rectangle rectExit = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_EXIT_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectExit, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    DrawTextEx(Var_GetFontRegular(), EXIT_TXT, exit, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw power off section
    Vector2 powerOff = {POWER_OFF_X, POWER_OFF_Y};
    Rectangle rectPowerOff = {
        PLAYPAUSE_SELECT_RECT_X,
        PLAYPAUSE_POWER_OFF_RECT_Y,
        PLAYPAUSE_SELECT_RECT_W,
        PLAYPAUSE_SELECT_RECT_H};
    DrawRectangleRoundedLinesEx(rectPowerOff, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, PLAYPAUSE_LINE_THICK, Var_GetColor3());
    DrawTextEx(Var_GetFontRegular(), POWER_OFF_TXT, powerOff, PLAYPAUSE_SIZE, PLAYPAUSE_SPACE, Var_GetColor3());
    //Draw select
    Vector2 selectSize = MeasureTextEx(Var_GetFontRegular(), SELECT_TXT, SELECT_SIZE, PLAYPAUSE_SPACE);
    Vector2 select = {SELECT_X, SELECT_Y};
    DrawTextEx(Var_GetFontRegular(), SELECT_TXT, select, SELECT_SIZE, PLAYPAUSE_SPACE, Fade(Var_GetColor3(), Var_GetAlphaSelect()));
    //Draw back
    Vector2 backSize = MeasureTextEx(Var_GetFontRegular(), BACK_TXT, BACK_SIZE, PLAYPAUSE_SPACE);
    Vector2 back = {BACK_X, BACK_Y};
    DrawTextEx(Var_GetFontRegular(), BACK_TXT, back, BACK_SIZE, PLAYPAUSE_SPACE, Fade(Var_GetColor3(), Var_GetAlphaSelect()));
    //Draw an outline around the selected section
    if (currentPlayPauseState == PLAYPAUSE_RESUME) {
        DrawRectangleRoundedLinesEx(rectResume, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1());
    }
    else if (currentPlayPauseState == PLAYPAUSE_RESTART) {
        DrawRectangleRoundedLinesEx(rectRestart, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1());
    }
    else if (currentPlayPauseState == PLAYPAUSE_CONTROLS) {
        DrawRectangleRoundedLinesEx(rectControls, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1());
    }
    else if (currentPlayPauseState == PLAYPAUSE_DIAGNOSTICS) {
        DrawRectangleRoundedLinesEx(rectDiag, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1());
    }
    else if (currentPlayPauseState == PLAYPAUSE_EXIT){
        DrawRectangleRoundedLinesEx(rectExit, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1());
    }
    else if (currentPlayPauseState == PLAYPAUSE_POWER_OFF){
       DrawRectangleRoundedLinesEx(rectPowerOff, PLAYPAUSE_ROUND, PLAYPAUSE_SEGMENTS, 2 * PLAYPAUSE_LINE_THICK, Var_GetColor1()); 
    }
}

//Inputs to go down a section
static bool PlayPause_Down(void) {
    return (IsKeyPressed(KEY_DOWN)) || ((IsKeyDown(KEY_DOWN) || LS_DOWN) && playPauseTimeElapsed >= SELECT_TIME);
}

//Inputs to go up a section
static bool PlayPause_Up(void) {
    return (IsKeyPressed(KEY_UP)) || ((IsKeyDown(KEY_UP) || LS_UP) && playPauseTimeElapsed >= SELECT_TIME);
}

//Inputs to resume games
static bool PlayPause_Resume(void) {
    return (HOME_PRESS && !Controller_GetWasPressed_Home()) || ((IsKeyPressed(KEY_ESCAPE) || B_PRESS) && !Controller_GetWasPressed_B());
}

//Inputs to select a section
static bool PlayPause_Select(void) {
    return (IsKeyPressed(KEY_ENTER) || A_PRESS) && !Controller_GetWasPressed_A();
}

//Exit the pause menu
static PlayState PlayPause_Exit(PlayState returnState) {
    //Unload controls image texture
    UnloadTexture(controlsImg);
    UnloadTexture(keyImg);
    UnloadTexture(mouseImg);
    UnloadTexture(arrowsImg);
    //Set controller variables
    Controller_SetWasPressed_A(true);
    Controller_SetWasPressed_B(true);
    Controller_SetWasPressed_Home(true);
    return returnState;
}

//PlayPause initialization
void PlayPause_Init(void) {
    //Load images
    controlsImg = LoadTexture("assets/images/other/controller.png");
    keyImg = LoadTexture("assets/images/other/keyboard.png");
    mouseImg = LoadTexture("assets/images/other/mouse.png");
    arrowsImg = LoadTexture("assets/images/other/arrow_keys.png");
    playPauseTimeElapsed = 0.0f;
    currentPlayPauseState = PLAYPAUSE_RESUME;
    displayControls = false;
    //Set controls to pressed
    Controller_SetWasPressed_A(true);
    Controller_SetWasPressed_B(true);
    Controller_SetWasPressed_Home(true);
}

//PlayPause tick
PlayState PlayPause_Tick(void) {
    //Transition
    switch (currentPlayPauseState) {
        //Resume game section
        case PLAYPAUSE_RESUME:
            //Move up or down a section
            if (PlayPause_Down()) {
                currentPlayPauseState = PLAYPAUSE_RESTART;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up()) {
                currentPlayPauseState = PLAYPAUSE_POWER_OFF;
                playPauseTimeElapsed = 0.0f;
            }
            break;

        //Restart game section
        case PLAYPAUSE_RESTART:
            //Move up or down a section
            if (PlayPause_Down()) {
                currentPlayPauseState = PLAYPAUSE_CONTROLS;
                displayControls = false;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                playPauseTimeElapsed = 0.0f;
            }
            break;

        //View controls section
        case PLAYPAUSE_CONTROLS:
            //Move up or down a section
            if (PlayPause_Down() && !displayControls) {
                currentPlayPauseState = PLAYPAUSE_DIAGNOSTICS;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up() && !displayControls) {
                currentPlayPauseState = PLAYPAUSE_RESTART;
                playPauseTimeElapsed = 0.0f;
            }
            break;

        //Display/hide diagnostics section
        case PLAYPAUSE_DIAGNOSTICS:
            //Move up or down a section
            if (PlayPause_Down()) {
                currentPlayPauseState = PLAYPAUSE_EXIT;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up()) {
                currentPlayPauseState = PLAYPAUSE_CONTROLS;
                displayControls = false;
                playPauseTimeElapsed = 0.0f;
            }
            break;

        //Exit game section
        case PLAYPAUSE_EXIT:
            //Move up or down a section
            if (PlayPause_Down()) {
                currentPlayPauseState = PLAYPAUSE_POWER_OFF;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up()) {
                currentPlayPauseState = PLAYPAUSE_DIAGNOSTICS;
                playPauseTimeElapsed = 0.0f;
            }
            break;
        
        case PLAYPAUSE_POWER_OFF:
            //Move up or down a section
            if (PlayPause_Down()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                playPauseTimeElapsed = 0.0f;
            }
            else if (PlayPause_Up()) {
                currentPlayPauseState = PLAYPAUSE_EXIT;
                playPauseTimeElapsed = 0.0f;
            }
            break;
    }

    //Action
    switch (currentPlayPauseState) {
        //Resume game section
        case PLAYPAUSE_RESUME:
            //Resume game
            if (PlayPause_Select()) {
                return PlayPause_Exit(PLAY_RESUME);
            }
            else if (PlayPause_Resume()) {
                return PlayPause_Exit(PLAY_RESUME);
            }
            UI_ChangeAlpha_Static();
            PlayPause_Draw();
            PlayPause_UpdateTime();
            break;

        //Restart game section
        case PLAYPAUSE_RESTART:
            //Restart game
            if (PlayPause_Select()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                return PlayPause_Exit(PLAY_RESTART);
            }
            //Resume game
            if (PlayPause_Resume()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                return PlayPause_Exit(PLAY_RESUME);
            }
            UI_ChangeAlpha_Static();
            PlayPause_Draw();
            PlayPause_UpdateTime();
            break;

        //View controls section
        case PLAYPAUSE_CONTROLS:
            //Stop or start displaying controls
            if (PlayPause_Select()) {
                displayControls = true;
                Controller_SetWasPressed_A(true);
            }
            //If B is pressed
            else if (PlayPause_Resume()) {
                //Resume game or stop displaying controls
                if (displayControls == false || HOME_DOWN) {
                    currentPlayPauseState = PLAYPAUSE_RESUME;
                    return PlayPause_Exit(PLAY_RESUME);
                }
                else {
                    Controller_SetWasPressed_B(true);
                    Controller_SetWasPressed_Home(true);
                    displayControls = false;
                }
            }
            //Draw controls or pause menu
            if (displayControls == true) {
                PlayPause_DrawControls(Games_GetDisplayed(3));
            }
            else {
                PlayPause_Draw();
            }
            UI_ChangeAlpha_Static();
            PlayPause_UpdateTime();
            break;

        //Display/hide diagnostics section
        case PLAYPAUSE_DIAGNOSTICS:
            //Stop or start displaying diagnostics
            if (PlayPause_Select()) {
                Var_SetDiag(!(Var_GetDiag()));
                Var_UpdateUIFile();
                Controller_SetWasPressed_A(true);
            }
            //Resume game
            if (PlayPause_Resume()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                return PlayPause_Exit(PLAY_RESUME);
            }
            UI_ChangeAlpha_Static();
            PlayPause_Draw();
            PlayPause_UpdateTime();
            break;

        //Exit game section
        case PLAYPAUSE_EXIT:
            //Exit game
            if (PlayPause_Select()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                return PlayPause_Exit(PLAY_EXIT);
            }
            //Resume game
            if (PlayPause_Resume()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
               return PlayPause_Exit(PLAY_RESUME);
            }
            UI_ChangeAlpha_Static();
            PlayPause_Draw();
            PlayPause_UpdateTime();
            break;
        
        case PLAYPAUSE_POWER_OFF:
            //Power off
            if (PlayPause_Select()) {
                Var_SetPowerOff(true);
                return PlayPause_Exit(PLAY_EXIT);
            }
            //Resume game
            if (PlayPause_Resume()) {
                currentPlayPauseState = PLAYPAUSE_RESUME;
                return PlayPause_Exit(PLAY_RESUME);
            }
            UI_ChangeAlpha_Static();
            PlayPause_Draw();
            PlayPause_UpdateTime();
            break;
    }
    return PLAY_PAUSE;
}
