#ifndef CONTROLSDISPLAY_CONFIG_H
#define CONTROLSDISPLAY_CONFIG_H

//Shared macros for the controls
#define PLAYPAUSE_CONTROL_SIZE (Var_GetMonitorWidth() / 75.0f)
#define PLAYPAUSE_CONTROL_SPACE (Var_GetMonitorWidth() / 2000.0f)
#define PLAYPAUSE_CONTROL_RADIUS (Var_GetMonitorWidth() / 70.0f)
//Right face buttons
#define PLAYPAUSE_RIGHT_FACE_DOWN_X (Var_GetMonitorWidth() / 1600 * 1187)
#define PLAYPAUSE_RIGHT_FACE_DOWN_Y (Var_GetMonitorHeight() / 400 * 193)
#define PLAYPAUSE_RIGHT_FACE_DOWN_TXT_X (PLAYPAUSE_RIGHT_FACE_DOWN_X - rDown_Size.x / 2)
#define PLAYPAUSE_RIGHT_FACE_DOWN_TXT_Y (PLAYPAUSE_RIGHT_FACE_DOWN_Y - rDown_Size.y / 2)
#define PLAYPAUSE_RIGHT_FACE_RIGHT_X (Var_GetMonitorWidth() / 1600 * 1238)
#define PLAYPAUSE_RIGHT_FACE_RIGHT_Y (Var_GetMonitorHeight() / 400 * 175)
#define PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_X (PLAYPAUSE_RIGHT_FACE_RIGHT_X - rRight_Size.x / 2)
#define PLAYPAUSE_RIGHT_FACE_RIGHT_TXT_Y (PLAYPAUSE_RIGHT_FACE_RIGHT_Y - rRight_Size.y / 2)
#define PLAYPAUSE_RIGHT_FACE_UP_X (Var_GetMonitorWidth() / 1600 * 1187)
#define PLAYPAUSE_RIGHT_FACE_UP_Y (Var_GetMonitorHeight() / 400 * 157)
#define PLAYPAUSE_RIGHT_FACE_UP_TXT_X (PLAYPAUSE_RIGHT_FACE_UP_X - rUp_Size.x / 2)
#define PLAYPAUSE_RIGHT_FACE_UP_TXT_Y (PLAYPAUSE_RIGHT_FACE_UP_Y - rUp_Size.y / 2)
#define PLAYPAUSE_RIGHT_FACE_LEFT_X (Var_GetMonitorWidth() / 1600 * 1136)
#define PLAYPAUSE_RIGHT_FACE_LEFT_Y (Var_GetMonitorHeight() / 400 * 175)
#define PLAYPAUSE_RIGHT_FACE_LEFT_TXT_X (PLAYPAUSE_RIGHT_FACE_LEFT_X - rLeft_Size.x / 2)
#define PLAYPAUSE_RIGHT_FACE_LEFT_TXT_Y (PLAYPAUSE_RIGHT_FACE_LEFT_Y - rLeft_Size.y / 2)
//Middle buttons
#define PLAYPAUSE_HOME_RECT_W (Var_GetMonitorWidth() / 23.0f)
#define PLAYPAUSE_HOME_RECT_H (Var_GetMonitorHeight() / 30.0f)
#define PLAYPAUSE_HOME_RECT_X (Var_GetMonitorWidth() / 800.0f * 375)
#define PLAYPAUSE_HOME_RECT_Y (Var_GetMonitorHeight() / 400.0f * 274)
#define PLAYPAUSE_HOME_TXT_X (PLAYPAUSE_HOME_RECT_X + PLAYPAUSE_HOME_RECT_W / 2 - home_Size.x / 2)
#define PLAYPAUSE_HOME_TXT_Y (PLAYPAUSE_HOME_RECT_Y + PLAYPAUSE_HOME_RECT_H / 2 - home_Size.y / 2)
#define PLAYPAUSE_BACK_RECT_W (Var_GetMonitorWidth() / 22.0f)
#define PLAYPAUSE_BACK_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_BACK_RECT_X (Var_GetMonitorWidth() / 800.0f * 335)
#define PLAYPAUSE_BACK_RECT_Y (Var_GetMonitorHeight() / 400.0f * 101)
#define PLAYPAUSE_BACK_TXT_X (PLAYPAUSE_BACK_RECT_X + PLAYPAUSE_BACK_RECT_W / 2 - back_Size.x / 2)
#define PLAYPAUSE_BACK_TXT_Y (PLAYPAUSE_BACK_RECT_Y + PLAYPAUSE_BACK_RECT_H / 2 - back_Size.y / 2)
#define PLAYPAUSE_START_RECT_W (Var_GetMonitorWidth() / 22.0f)
#define PLAYPAUSE_START_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_START_RECT_X (Var_GetMonitorWidth() / 800.0f * 413)
#define PLAYPAUSE_START_RECT_Y (Var_GetMonitorHeight() / 400.0f * 101)
#define PLAYPAUSE_START_TXT_X (PLAYPAUSE_START_RECT_X + PLAYPAUSE_START_RECT_W / 2 - start_Size.x / 2)
#define PLAYPAUSE_START_TXT_Y (PLAYPAUSE_START_RECT_Y + PLAYPAUSE_START_RECT_H / 2 - start_Size.y / 2)
//D-Pad
#define PLAYPAUSE_D_RECT_W (Var_GetMonitorWidth() / 23.0f)
#define PLAYPAUSE_D_RECT_H (Var_GetMonitorHeight() / 30.0f)
#define PLAYPAUSE_D_RECT_X (Var_GetMonitorWidth() / 800.0f * 320)
#define PLAYPAUSE_D_RECT_Y (Var_GetMonitorHeight() / 400.0f * 273)
#define PLAYPAUSE_D_TXT_X (PLAYPAUSE_D_RECT_X + PLAYPAUSE_D_RECT_W / 2 - d_Size.x / 2)
#define PLAYPAUSE_D_TXT_Y (PLAYPAUSE_D_RECT_Y + PLAYPAUSE_D_RECT_H / 2 - d_Size.y / 2)
//Joysticks
#define PLAYPAUSE_RS_RECT_W (Var_GetMonitorWidth() / 21.0f)
#define PLAYPAUSE_RS_RECT_H (Var_GetMonitorHeight() / 30.0f)
#define PLAYPAUSE_RS_RECT_X (Var_GetMonitorWidth() / 800.0f * 426)
#define PLAYPAUSE_RS_RECT_Y (Var_GetMonitorHeight() / 400.0f * 273)
#define PLAYPAUSE_RS_TXT_X (PLAYPAUSE_RS_RECT_X + PLAYPAUSE_RS_RECT_W / 2 - rs_Size.x / 2)
#define PLAYPAUSE_RS_TXT_Y (PLAYPAUSE_RS_RECT_Y + PLAYPAUSE_RS_RECT_H / 2 - rs_Size.y / 2)
#define PLAYPAUSE_LS_RECT_W (Var_GetMonitorWidth() / 21.0f)
#define PLAYPAUSE_LS_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_LS_RECT_X (Var_GetMonitorWidth() / 800.0f * 182)
#define PLAYPAUSE_LS_RECT_Y (Var_GetMonitorHeight() / 400.0f * 169)
#define PLAYPAUSE_LS_TXT_X (PLAYPAUSE_LS_RECT_X + PLAYPAUSE_LS_RECT_W / 2 - ls_Size.x / 2)
#define PLAYPAUSE_LS_TXT_Y (PLAYPAUSE_LS_RECT_Y + PLAYPAUSE_LS_RECT_H / 2 - ls_Size.y / 2)
//Triggers
#define PLAYPAUSE_LT_RECT_W (Var_GetMonitorWidth() / 22.0f)
#define PLAYPAUSE_LT_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_LT_RECT_X (Var_GetMonitorWidth() / 800.0f * 268)
#define PLAYPAUSE_LT_RECT_Y (Var_GetMonitorHeight() / 400.0f * 101)
#define PLAYPAUSE_LT_TXT_X (PLAYPAUSE_LT_RECT_X + PLAYPAUSE_LT_RECT_W / 2 - lt_Size.x / 2)
#define PLAYPAUSE_LT_TXT_Y (PLAYPAUSE_LT_RECT_Y + PLAYPAUSE_LT_RECT_H / 2 - lt_Size.y / 2)
#define PLAYPAUSE_RT_RECT_W (Var_GetMonitorWidth() / 22.0f)
#define PLAYPAUSE_RT_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_RT_RECT_X (Var_GetMonitorWidth() / 800.0f * 479)
#define PLAYPAUSE_RT_RECT_Y (Var_GetMonitorHeight() / 400.0f * 101)
#define PLAYPAUSE_RT_TXT_X (PLAYPAUSE_RT_RECT_X + PLAYPAUSE_RT_RECT_W / 2 - rt_Size.x / 2)
#define PLAYPAUSE_RT_TXT_Y (PLAYPAUSE_RT_RECT_Y + PLAYPAUSE_RT_RECT_H / 2 - rt_Size.y / 2)
//Bumpers
#define PLAYPAUSE_LB_RECT_W (Var_GetMonitorWidth() / 26.0f)
#define PLAYPAUSE_LB_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_LB_RECT_X (Var_GetMonitorWidth() / 800.0f * 209)
#define PLAYPAUSE_LB_RECT_Y (Var_GetMonitorHeight() / 400.0f * 135)
#define PLAYPAUSE_LB_TXT_X (PLAYPAUSE_LB_RECT_X + PLAYPAUSE_LB_RECT_W / 2 - lb_Size.x / 2)
#define PLAYPAUSE_LB_TXT_Y (PLAYPAUSE_LB_RECT_Y + PLAYPAUSE_LB_RECT_H / 2 - lb_Size.y / 2)
#define PLAYPAUSE_RB_RECT_W (Var_GetMonitorWidth() / 26.0f)
#define PLAYPAUSE_RB_RECT_H (Var_GetMonitorHeight() / 31.0f)
#define PLAYPAUSE_RB_RECT_X (Var_GetMonitorWidth() / 800.0f * 544)
#define PLAYPAUSE_RB_RECT_Y (Var_GetMonitorHeight() / 400.0f * 135)
#define PLAYPAUSE_RB_TXT_X (PLAYPAUSE_RB_RECT_X + PLAYPAUSE_RB_RECT_W / 2 - rb_Size.x / 2)
#define PLAYPAUSE_RB_TXT_Y (PLAYPAUSE_RB_RECT_Y + PLAYPAUSE_RB_RECT_H / 2 - rb_Size.y / 2)


#endif