#ifndef CONTROLSDISPLAY_CONFIG_H
#define CONTROLSDISPLAY_CONFIG_H

//Shared macros for the controls
#define CONTROL_SIZE (SCREEN_W / 75.0f)
#define CONTROL_SPACE (SCREEN_W / 2000.0f)
#define CONTROL_RADIUS (SCREEN_W / 70.0f)
//Right face buttons
#define RIGHT_FACE_DOWN_X (SCREEN_W / 400 * 356)
#define RIGHT_FACE_DOWN_Y (SCREEN_H / 200 * 104)
#define RIGHT_FACE_DOWN_TXT_X (RIGHT_FACE_DOWN_X - rDown_Size.x / 2)
#define RIGHT_FACE_DOWN_TXT_Y (RIGHT_FACE_DOWN_Y - rDown_Size.y / 2)
#define RIGHT_FACE_RIGHT_X (SCREEN_W / 800 * 742)
#define RIGHT_FACE_RIGHT_Y (SCREEN_H / 200 * 95)
#define RIGHT_FACE_RIGHT_TXT_X (RIGHT_FACE_RIGHT_X - rRight_Size.x / 2)
#define RIGHT_FACE_RIGHT_TXT_Y (RIGHT_FACE_RIGHT_Y - rRight_Size.y / 2)
#define RIGHT_FACE_UP_X (SCREEN_W / 400 * 356)
#define RIGHT_FACE_UP_Y (SCREEN_H / 200 * 85)
#define RIGHT_FACE_UP_TXT_X (RIGHT_FACE_UP_X - rUp_Size.x / 2)
#define RIGHT_FACE_UP_TXT_Y (RIGHT_FACE_UP_Y - rUp_Size.y / 2)
#define RIGHT_FACE_LEFT_X (SCREEN_W / 800 * 681)
#define RIGHT_FACE_LEFT_Y (SCREEN_H / 200 * 95)
#define RIGHT_FACE_LEFT_TXT_X (RIGHT_FACE_LEFT_X - rLeft_Size.x / 2)
#define RIGHT_FACE_LEFT_TXT_Y (RIGHT_FACE_LEFT_Y - rLeft_Size.y / 2)
//Middle buttons
#define HOME_RECT_W (SCREEN_W / 23.0f)
#define HOME_RECT_H (SCREEN_H / 30.0f)
#define HOME_RECT_X (SCREEN_W / 800.0f * 375)
#define HOME_RECT_Y (SCREEN_H / 400.0f * 274)
#define HOME_TXT_X (HOME_RECT_X + HOME_RECT_W / 2 - home_Size.x / 2)
#define HOME_TXT_Y (HOME_RECT_Y + HOME_RECT_H / 2 - home_Size.y / 2)
#define BACK_RECT_W (SCREEN_W / 22.0f)
#define BACK_RECT_H (SCREEN_H / 31.0f)
#define BACK_RECT_X (SCREEN_W / 800.0f * 335)
#define BACK_RECT_Y (SCREEN_H / 400.0f * 101)
#define BACK_TXT_X (BACK_RECT_X + BACK_RECT_W / 2 - back_Size.x / 2)
#define BACK_TXT_Y (BACK_RECT_Y + BACK_RECT_H / 2 - back_Size.y / 2)
#define START_RECT_W (SCREEN_W / 22.0f)
#define START_RECT_H (SCREEN_H / 31.0f)
#define START_RECT_X (SCREEN_W / 800.0f * 413)
#define START_RECT_Y (SCREEN_H / 400.0f * 101)
#define START_TXT_X (START_RECT_X + START_RECT_W / 2 - start_Size.x / 2)
#define START_TXT_Y (START_RECT_Y + START_RECT_H / 2 - start_Size.y / 2)
//D-Pad
#define D_RECT_W (SCREEN_W / 23.0f)
#define D_RECT_H (SCREEN_H / 30.0f)
#define D_RECT_X (SCREEN_W / 800.0f * 320)
#define D_RECT_Y (SCREEN_H / 400.0f * 273)
#define D_TXT_X (D_RECT_X + D_RECT_W / 2 - d_Size.x / 2)
#define D_TXT_Y (D_RECT_Y + D_RECT_H / 2 - d_Size.y / 2)
//Joysticks
#define RS_RECT_W (SCREEN_W / 21.0f)
#define RS_RECT_H (SCREEN_H / 30.0f)
#define RS_RECT_X (SCREEN_W / 800.0f * 426)
#define RS_RECT_Y (SCREEN_H / 400.0f * 273)
#define RS_TXT_X (RS_RECT_X + RS_RECT_W / 2 - rs_Size.x / 2)
#define RS_TXT_Y (RS_RECT_Y + RS_RECT_H / 2 - rs_Size.y / 2)
#define LS_RECT_W (SCREEN_W / 21.0f)
#define LS_RECT_H (SCREEN_H / 31.0f)
#define LS_RECT_X (SCREEN_W / 800.0f * 182)
#define LS_RECT_Y (SCREEN_H / 400.0f * 169)
#define LS_TXT_X (LS_RECT_X + LS_RECT_W / 2 - ls_Size.x / 2)
#define LS_TXT_Y (LS_RECT_Y + LS_RECT_H / 2 - ls_Size.y / 2)
//Triggers
#define LT_RECT_W (SCREEN_W / 22.0f)
#define LT_RECT_H (SCREEN_H / 31.0f)
#define LT_RECT_X (SCREEN_W / 800.0f * 268)
#define LT_RECT_Y (SCREEN_H / 400.0f * 101)
#define LT_TXT_X (LT_RECT_X + LT_RECT_W / 2 - lt_Size.x / 2)
#define LT_TXT_Y (LT_RECT_Y + LT_RECT_H / 2 - lt_Size.y / 2)
#define RT_RECT_W (SCREEN_W / 22.0f)
#define RT_RECT_H (SCREEN_H / 31.0f)
#define RT_RECT_X (SCREEN_W / 800.0f * 479)
#define RT_RECT_Y (SCREEN_H / 400.0f * 101)
#define RT_TXT_X (RT_RECT_X + RT_RECT_W / 2 - rt_Size.x / 2)
#define RT_TXT_Y (RT_RECT_Y + RT_RECT_H / 2 - rt_Size.y / 2)
//Bumpers
#define LB_RECT_W (SCREEN_W / 26.0f)
#define LB_RECT_H (SCREEN_H / 31.0f)
#define LB_RECT_X (SCREEN_W / 800.0f * 209)
#define LB_RECT_Y (SCREEN_H / 400.0f * 135)
#define LB_TXT_X (LB_RECT_X + LB_RECT_W / 2 - lb_Size.x / 2)
#define LB_TXT_Y (LB_RECT_Y + LB_RECT_H / 2 - lb_Size.y / 2)
#define RB_RECT_W (SCREEN_W / 26.0f)
#define RB_RECT_H (SCREEN_H / 31.0f)
#define RB_RECT_X (SCREEN_W / 800.0f * 544)
#define RB_RECT_Y (SCREEN_H / 400.0f * 135)
#define RB_TXT_X (RB_RECT_X + RB_RECT_W / 2 - rb_Size.x / 2)
#define RB_TXT_Y (RB_RECT_Y + RB_RECT_H / 2 - rb_Size.y / 2)


#endif