#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#pragma region UI_GENERAL
//General setup definitions
#define FPS 60


#define MENU_IMG_Y_CENTER (SCREEN_H * (11.0f / 20))
#pragma endregion

#pragma region UI_BOOT
//Width and length of logo
#define LOGO_SIZE (SCREEN_H / 8 * 9)
#pragma endregion



#pragma region UI_CATEGORIES_SCROLL
#define SCROLL_CATEG_IN_SPEED 0.15f
#define SCROLL_CATEG_OUT_SPEED 0.225f
#define SCROLL_CATEG_THRESHOLD (SCREEN_W / 80.0f)

#define LEFT2_SCROLLR (LEFT1_SCROLLR - (SIDE2_GAME_W * (19 / 20.0f)))
#define LEFT1_SCROLLR (CENTER_SCROLLR - (SIDE1_GAME_W * (19 / 20.0f)))
#define CENTER_SCROLLR (- SCREEN_W * (1.0f / 4))
#define RIGHT1_SCROLLR (CENTER_SCROLLR + (SIDE1_GAME_W * (19 / 20.0f)))
#define RIGHT2_SCROLLR (RIGHT1_SCROLLR + (SIDE2_GAME_W * (19 / 20.0f)))

#define LEFT2_SCROLLR_X (UI_CenterImg_X(SIDE2_GAME_W, LEFT2_SCROLLR))
#define LEFT1_SCROLLR_X (UI_CenterImg_X(SIDE1_GAME_W, LEFT1_SCROLLR))
#define CENTER_SCROLLR_X (UI_CenterImg_X(CENTER_GAME_W, CENTER_SCROLLR))
#define RIGHT1_SCROLLR_X (UI_CenterImg_X(SIDE1_GAME_W, RIGHT1_SCROLLR))
#define RIGHT2_SCROLLR_X (UI_CenterImg_X(SIDE2_GAME_W, RIGHT2_SCROLLR))

#define LEFT2_SCROLLL (LEFT1_SCROLLL - (SIDE2_GAME_W * (19 / 20.0f)))
#define LEFT1_SCROLLL (CENTER_SCROLLL - (SIDE1_GAME_W * (19 / 20.0f)))
#define CENTER_SCROLLL (SCREEN_W * (5.0f / 4))
#define RIGHT1_SCROLLL (CENTER_SCROLLL + (SIDE1_GAME_W * (19 / 20.0f)))
#define RIGHT2_SCROLLL (RIGHT1_SCROLLL + (SIDE2_GAME_W * (19 / 20.0f)))

#define LEFT2_SCROLLL_X (UI_CenterImg_X(SIDE2_GAME_W, LEFT2_SCROLLL))
#define LEFT1_SCROLLL_X (UI_CenterImg_X(SIDE1_GAME_W, LEFT1_SCROLLL))
#define CENTER_SCROLLL_X (UI_CenterImg_X(CENTER_GAME_W, CENTER_SCROLLL))
#define RIGHT1_SCROLLL_X (UI_CenterImg_X(SIDE1_GAME_W, RIGHT1_SCROLLL))
#define RIGHT2_SCROLLL_X (UI_CenterImg_X(SIDE2_GAME_W, RIGHT2_SCROLLL))
#pragma endregion



#pragma region UI_DIAGNOSTICS
#define DIAGNOSTICS_TITLE "System Diagnostics"
#define DIAGNOSTICS_TITLE_SIZE (SCREEN_W / 25.0f)
#define DIAGNOSTICS_TITLE_X (CENTER_X - diagnosticsTitle_Size.x / 2)
#define DIAGNOSTICS_TITLE_Y (SCREEN_H / 12.0f)
#define DIAGNOSTICS_TITLE_TXT_Y (DIAGNOSTICS_TITLE_Y - diagnosticsTitle_Size.x / 2)

#define DIAGNOSTICS_SIZE (SCREEN_W / 35.0f)
#define DIAGNOSTICS_SPACING (SCREEN_W / 400.0f)
#define RESOLUTION_TXT_X (FPS_TXT_X)
#define RESOLUTION_TXT_Y (SCREEN_H / 4.0f)


#define FPS_TXT_X (SCREEN_W / 10.0f)
#define FPS_TXT_Y (RESOLUTION_TXT_Y + SCREEN_H / 12.0f)

#pragma endregion


#pragma region UI_OPTIONS_MENU
#define OPTIONS_RECT_X (CENTER_X - OPTIONS_RECT_W / 2)
#define OPTIONS_RECT_Y (SCREEN_H * (1.0f / 2) - OPTIONS_RECT_H / 2)
#define OPTIONS_RECT_W (SCREEN_W * (2.0f / 5))
#define OPTIONS_RECT_H (SCREEN_H * (2.0f / 5))
#define OPTIONS_ROUND 0.025f
#define OPTIONS_SEGMENTS 15

#define OPTIONS_TXT_SPACING_Y (SCREEN_H / 30.0f)
#define OPTIONS_TITLE "[OPTIONS]"
#define OPTIONS_TITLE_SIZE (SCREEN_W / 40.0f)
#define OPTIONS_TITLE_SPACE (SCREEN_W / 400.0f)
#define OPTIONS_TITLE_X (CENTER_X - optionsTitle_Size.x / 2)
#define OPTIONS_TITLE_Y (OPTIONS_RECT_Y + OPTIONS_TXT_SPACING_Y - optionsTitle_Size.y / 2)

#define OPTIONS_VIEW_LIST "View games/consoles list"
#define OPTIONS_VIEW_LIST_SIZE (OPTIONS_TITLE_SIZE * (3.0f / 4))
#define OPTIONS_VIEW_LIST_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_VIEW_LIST_Y (OPTIONS_TITLE_Y + optionsTitle_Size.y + OPTIONS_TXT_SPACING_Y - optionsList_Size.y / 2)


#define OPTIONS_BRIGHTNESS "Adjust brightness"
#define OPTIONS_BRIGHTNESS_SIZE (OPTIONS_TITLE_SIZE * (3.0f / 4))
#define OPTIONS_BRIGHTNESS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_BRIGHTNESS_Y (OPTIONS_VIEW_LIST_Y + optionsList_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6)  - optionsBrightness_Size.y / 2)

#define OPTIONS_THEME "Select theme"
#define OPTIONS_THEME_SIZE (OPTIONS_TITLE_SIZE * (3.0f / 4))
#define OPTIONS_THEME_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_THEME_Y (OPTIONS_BRIGHTNESS_Y + optionsBrightness_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - optionsTheme_Size.y / 2)

#define OPTIONS_DISPLAY_DIAGNOSTICS "Display diagnostics"
#define OPTIONS_HIDE_DIAGNOSTICS "Hide diagnostics"
#define OPTIONS_DISPLAY_DIAGNOSTICS_SIZE (OPTIONS_TITLE_SIZE * (3.0f / 4))
#define OPTIONS_DISPLAY_DIAGNOSTICS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_DISPLAY_DIAGNOSTICS_Y (OPTIONS_THEME_Y + optionsTheme_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - optionsDisplayDiagnostics_Size.y / 2)

#define OPTIONS_DIAGNOSTICS "View diagnostics menu"
#define OPTIONS_MAIN "View main menu"
#define OPTIONS_DIAGNOSTICS_SIZE (OPTIONS_TITLE_SIZE * (3.0f / 4))
#define OPTIONS_DIAGNOSTICS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_DIAGNOSTICS_Y (OPTIONS_DISPLAY_DIAGNOSTICS_Y + optionsDisplayDiagnostics_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - optionsDiagnostics_Size.y / 2)

#define OPTIONS_SELECT "[A/X] SELECT"
#define OPTIONS_SELECT_SIZE (OPTIONS_TITLE_SIZE * (1.0f / 2))
#define OPTIONS_SELECT_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define OPTIONS_SELECT_Y (OPTIONS_RECT_Y + OPTIONS_RECT_H - OPTIONS_TXT_SPACING_Y / 2 - optionsSelect_Size.y)

#define OPTIONS_BACK "[B/O] BACK"
#define OPTIONS_BACK_SIZE (OPTIONS_TITLE_SIZE * (1.0f / 2))
#define OPTIONS_BACK_X (OPTIONS_RECT_X + OPTIONS_RECT_W - OPTIONS_TXT_SPACING_Y - optionsBack_Size.x)
#define OPTIONS_BACK_Y (OPTIONS_RECT_Y + OPTIONS_RECT_H - OPTIONS_TXT_SPACING_Y / 2 - optionsBack_Size.y)

#define OPTIONS_SELECT_RECT_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y / 2)
#define OPTIONS_SELECT_RECT_W (OPTIONS_RECT_W - OPTIONS_TXT_SPACING_Y)
#define OPTIONS_SELECT_RECT_H (optionsList_Size.y + OPTIONS_TXT_SPACING_Y / 4)
#define OPTIONS_VIEW_LIST_RECT_Y (OPTIONS_VIEW_LIST_Y - OPTIONS_TXT_SPACING_Y / 16)
#define OPTIONS_BRIGHTNESS_RECT_Y (OPTIONS_BRIGHTNESS_Y - OPTIONS_TXT_SPACING_Y / 16)
#define OPTIONS_THEME_RECT_Y (OPTIONS_THEME_Y - OPTIONS_TXT_SPACING_Y / 16)
#define OPTIONS_DISPLAY_DIAGNOSTICS_RECT_Y (OPTIONS_DISPLAY_DIAGNOSTICS_Y - OPTIONS_TXT_SPACING_Y / 16)
#define OPTIONS_DIAGNOSTICS_RECT_Y (OPTIONS_DIAGNOSTICS_Y - OPTIONS_TXT_SPACING_Y / 16)

#define BRIGHTNESS_TXT "Adjust brightness"
#define BRIGHTNESS_TXT_SIZE (SCREEN_W / 40.0f)
#define BRIGHTNESS_TXT_SPACE (SCREEN_W / 400.0f)
#define BRIGHTNESS_TXT_X (CENTER_X - brightnessTxt_Size.x / 2)
#define BRIGHTNESS_TXT_Y (OPTIONS_RECT_Y + OPTIONS_TXT_SPACING_Y - brightnessTxt_Size.y / 2)

#define BRIGHTNESS_LINE_X_START (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y * 2)
#define BRIGHTNESS_LINE_X_END (OPTIONS_RECT_X + OPTIONS_RECT_W - OPTIONS_TXT_SPACING_Y * 2)
#define BRIGHTNESS_LINE_Y (OPTIONS_RECT_Y + OPTIONS_RECT_H / 5 * 3)
#define BRIGHTNESS_LINE_THICK (SCREEN_H / 650.0f)
#define BRIGHTNESS_RADIUS (SCREEN_W / 90.0f)
#define BRIGHTNESS_CIRCLE_X (BRIGHTNESS_LINE_X_END - (brightness * 100) * BRIGHTNESS_CIRCLE_INCREMENT)
#define BRIGHTNESS_CIRCLE_INCREMENT ((BRIGHTNESS_LINE_X_END - BRIGHTNESS_LINE_X_START) / 100.0f)

#define BRIGHT_LS_LEFT_X (CENTER_X - SCREEN_W / 55.0f)
#define BRIGHT_LS_RIGHT_X (CENTER_X + SCREEN_W / 55.0f)
#define BRIGHT_LS_Y (BRIGHTNESS_LINE_Y + BRIGHT_LS_RADIUS + OPTIONS_TXT_SPACING_Y)
#define BRIGHT_LS_TRIANGLE_SIZE (SCREEN_W / 120.0f)
#define BRIGHT_LS_RADIUS (SCREEN_W / 135.0f)

#define BRIGHTNESS_PERCENT_SIZE (SCREEN_W / 60.0f)
#define BRIGHTNESS_PERCENT_X (CENTER_X - brightnessPercent_Size.x / 2)
#define BRIGHTNESS_PERCENT_Y (BRIGHTNESS_LINE_Y - 3 * OPTIONS_TXT_SPACING_Y / 2 - brightnessPercent_Size.y / 2)

#define MAX_BRIGHTNESS 0
#define MIN_BRIGHTNESS 200
#define BRIGHTNESS_INCREMENT (MIN_BRIGHTNESS / 100)

#define THEME_TXT "Select theme"
#define THEME_TXT_SIZE (SCREEN_W / 40.0f)
#define THEME_TXT_SPACE (SCREEN_W / 400.0f)
#define THEME_TXT_X (CENTER_X - themeTxt_Size.x / 2)
#define THEME_TXT_Y (OPTIONS_RECT_Y + OPTIONS_TXT_SPACING_Y - themeTxt_Size.y / 2)

#define THEME_RECT_X (OPTIONS_RECT_X + 2 * OPTIONS_TXT_SPACING_Y)
#define THEME_RECT_W (OPTIONS_RECT_W  - 4 * OPTIONS_TXT_SPACING_Y)
#define THEME_RECT_H (themeTxt_Size.y * 6.0f / 5)
#define THEME_RECT_1_Y (THEME_TXT_Y + themeTxt_Size.y + OPTIONS_TXT_SPACING_Y / 2.0f)
#define THEME_X2 (THEME_RECT_X + THEME_RECT_W / 3)
#define THEME_X3 (THEME_X2 + THEME_RECT_W / 3)
#define THEME_RECT_2_Y (THEME_RECT_1_Y + THEME_RECT_H + OPTIONS_TXT_SPACING_Y / 4.0f * 3)
#define THEME_RECT_3_Y (THEME_RECT_2_Y + THEME_RECT_H + OPTIONS_TXT_SPACING_Y / 4.0f * 3)
#define THEME_RECT_4_Y (THEME_RECT_3_Y + THEME_RECT_H + OPTIONS_TXT_SPACING_Y / 4.0f * 3)

#define DIAG_SIZE (SCREEN_W / 100.0f)
#define DIAG_SPACING (SCREEN_W / 800.0f)
#define DIAG_RES_X (DIAG_FPS_X)
#define DIAG_RES_Y (SCREEN_H / 70.0f)


#define DIAG_FPS_X (SCREEN_W / 70.0f)
#define DIAG_FPS_Y (DIAG_RES_Y + SCREEN_H / 40.0f)
#pragma endregion




#pragma region GAME_PAUSE

#define PAUSE_TXT_SPACING_Y (SCREEN_H / 30.0f)
#define PAUSE_TITLE "[PAUSED]"
#define PAUSE_TITLE_SIZE (SCREEN_W / 40.0f)
#define PAUSE_TITLE_SPACE (SCREEN_W / 400.0f)
#define PAUSE_TITLE_X (CENTER_X - pauseTitle_Size.x / 2)
#define PAUSE_TITLE_Y (OPTIONS_RECT_Y + OPTIONS_TXT_SPACING_Y - pauseTitle_Size.y / 2)

#define PAUSE_REST "Restart game"
#define PAUSE_REST_SIZE (PAUSE_TITLE_SIZE * (3.0f / 4))
#define PAUSE_REST_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_REST_Y (PAUSE_TITLE_Y + pauseTitle_Size.y + OPTIONS_TXT_SPACING_Y - pauseRest_Size.y / 2)

#define PAUSE_BRIGHTNESS "Adjust brightness"
#define PAUSE_BRIGHTNESS_SIZE (PAUSE_TITLE_SIZE * (3.0f / 4))
#define PAUSE_BRIGHTNESS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_BRIGHTNESS_Y (PAUSE_REST_Y + pauseRest_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6)  - pauseBrightness_Size.y / 2)

#define PAUSE_CONTROLS "View controls"
#define PAUSE_CONTROLS_SIZE (PAUSE_TITLE_SIZE * (3.0f / 4))
#define PAUSE_CONTROLS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_CONTROLS_Y (PAUSE_BRIGHTNESS_Y + pauseBrightness_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - pauseControls_Size.y / 2)

#define PAUSE_DISPLAY_DIAGNOSTICS "Display diagnostics"
#define PAUSE_HIDE_DIAGNOSTICS "Hide diagnostics"
#define PAUSE_DISPLAY_DIAGNOSTICS_SIZE (PAUSE_TITLE_SIZE * (3.0f / 4))
#define PAUSE_DISPLAY_DIAGNOSTICS_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_DISPLAY_DIAGNOSTICS_Y (PAUSE_CONTROLS_Y + pauseControls_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - pauseDisplayDiagnostics_Size.y / 2)


#define PAUSE_EXIT "Exit game"
#define PAUSE_EXIT_SIZE (PAUSE_TITLE_SIZE * (3.0f / 4))
#define PAUSE_EXIT_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_EXIT_Y (PAUSE_DISPLAY_DIAGNOSTICS_Y + pauseDisplayDiagnostics_Size.y + OPTIONS_TXT_SPACING_Y * (7.0f / 6) - pauseExit_Size.y / 2)

#define PAUSE_SELECT "[A/X] SELECT"
#define PAUSE_SELECT_SIZE (PAUSE_TITLE_SIZE * (1.0f / 2))
#define PAUSE_SELECT_X (OPTIONS_RECT_X + OPTIONS_TXT_SPACING_Y)
#define PAUSE_SELECT_Y (OPTIONS_RECT_Y + OPTIONS_RECT_H - OPTIONS_TXT_SPACING_Y / 2 - pauseSelect_Size.y)

#define PAUSE_BACK "[B/O] BACK"
#define PAUSE_BACK_SIZE (PAUSE_TITLE_SIZE * (1.0f / 2))
#define PAUSE_BACK_X (OPTIONS_RECT_X + OPTIONS_SELECT_RECT_W - OPTIONS_TXT_SPACING_Y - pauseBack_Size.x)
#define PAUSE_BACK_Y (OPTIONS_RECT_Y + OPTIONS_RECT_H - OPTIONS_TXT_SPACING_Y / 2 - pauseBack_Size.y)


#define PAUSE_SELECT_RECT_H (pauseRest_Size.y + OPTIONS_TXT_SPACING_Y / 4)
#define PAUSE_REST_RECT_Y (PAUSE_REST_Y - OPTIONS_TXT_SPACING_Y / 16)
#define PAUSE_BRIGHTNESS_RECT_Y (PAUSE_BRIGHTNESS_Y - OPTIONS_TXT_SPACING_Y / 16)
#define PAUSE_CONTROLS_RECT_Y (PAUSE_CONTROLS_Y - OPTIONS_TXT_SPACING_Y / 16)
#define PAUSE_DISPLAY_DIAGNOSTICS_RECT_Y (PAUSE_DISPLAY_DIAGNOSTICS_Y - OPTIONS_TXT_SPACING_Y / 16)
#define PAUSE_EXIT_RECT_Y (PAUSE_EXIT_Y - OPTIONS_TXT_SPACING_Y / 16)

#define RESUME_TXT "RESUMING..."
#define RESUME_X (SCREEN_W / 10.0f)
#define RESUME_Y (SCREEN_H / 8.0f)
#define RESUME_RECT_X (RESUME_X - SCREEN_W / 80.0f)
#define RESUME_RECT_Y (RESUME_Y - SCREEN_H / 80.0f)
#define RESUME_RECT_W (resumeTxt_Size.x + SCREEN_W / 40.0f)
#define RESUME_RECT_H (resumeTxt_Size.y + SCREEN_H / 40.0f)

#pragma endregion





#endif